// Drive: Google-Drive-like per-user cloud storage. Bytes live in R2 under drive/<owner_id>/<file_id>;
// the folder tree is D1 metadata (drive_nodes), so rename/move never copies data (R2 has no rename).
// The switch is per domain; a user has Drive when any of their domains enables it, and the storage
// pool is one per user across domains. Quota: per-user override, else the largest default among the
// user's enabled domains, hard-capped at 10 GB. Sharing: one link per folder, viewer/editor, only for
// signed-in users sharing at least one domain with the owner.
//
// 网盘:Google Drive 风格的每用户云存储。字节存 R2 的 drive/<owner_id>/<file_id>;
// 目录树是 D1 元数据(drive_nodes),改名/移动不搬数据(R2 没有重命名)。
// 开关按域名;用户所属任一域名开启即可用,存储跨域名同一份。
// 配额:用户单独指定优先,否则取其已开启域名中最大的默认值,硬顶 10TB。
// 共享:每文件夹一条链接,查看者/编辑者两档,仅限与所有者至少同属一个域名的登录用户。
import { Hono } from 'hono';
import type { Env, User } from './types';
import { HttpError } from './errors';
import { requireAuth } from './auth';
import { audit } from './audit';
import { now, randomToken, uid } from './util';
import { adminScope, checkDomainScope } from './admin';

const MB = 1024 * 1024;
export const DRIVE_HARD_CAP_MB = 10 * 1024 * 1024; // absolute per-user ceiling / 每用户绝对上限(10TB)
const SINGLE_MAX = 90 * MB;             // bigger uploads must go multipart / 超过必须走分片
const PART_SIZE = 32 * MB;              // suggested slice for the client / 建议前端的分片大小
const NAME_MAX = 255;
const DEPTH_MAX = 64;                   // folder nesting ceiling (also caps the recursive CTEs) / 目录深度上限(同时封顶递归查询)
const LIST_LIMIT = 1000;
const PURGE_BATCH = 300;                // permanent deletes per request, like mailbox purge / 每次请求彻底删除的节点数(同邮箱清空的思路)
const TRASH_KEEP_MS = 30 * 24 * 3600 * 1000;
const UPLOAD_STALE_MS = 24 * 3600 * 1000;
// Thumbnails: generated by the uploading client (WebP), stored beside the original
// 缩略图:由上传端生成(WebP),存在原文件 R2 键旁边
const THUMB_SUFFIX = '.t';
const THUMB_MAX_BYTES = 100 * 1024;

// Inline preview whitelist: nothing here may execute script under our origin. SVG and HTML must
// never enter this set (same trap the /cid endpoint once fell into); text/plain is pinned to UTF-8.
// 内联预览白名单:进这张表的类型都不能在本站源执行脚本。SVG 与 HTML 绝不能加进来
// (/cid 端点栽过的同一个坑);text/plain 强制 UTF-8。
const INLINE_MIMES = new Set([
  'image/png', 'image/jpeg', 'image/jpg', 'image/gif', 'image/webp', 'image/bmp', 'image/avif',
  'application/pdf', 'text/plain',
  'video/mp4', 'video/webm', 'video/ogg', 'video/quicktime',
  'audio/mpeg', 'audio/mp3', 'audio/mp4', 'audio/ogg', 'audio/wav', 'audio/x-wav', 'audio/webm',
  'audio/flac', 'audio/aac', 'audio/x-m4a',
]);

type Ctx = { Bindings: Env; Variables: { user: User; dq: Quota } };

interface Quota {
  enabled: boolean;
  quota: number; // bytes
  used: number;  // bytes
}

interface NodeRow {
  id: string;
  owner_id: string;
  parent_id: string | null;
  kind: 'folder' | 'file';
  name: string;
  mime: string;
  size: number;
  r2_key: string | null;
  starred: number;
  trashed: number;
  trashed_at: number | null;
  has_thumb: number;
  tree_bytes: number;
  created_at: number;
  updated_at: number;
}

// ---------- Quota and feature gate ----------
// ---------- 配额与功能开关 ----------

/** Effective quota and usage. enabled=false when none of the user's domains has Drive switched on.
 *  生效配额与用量。用户所属域名都没开网盘时 enabled=false。 */
export async function driveQuota(env: Env, userId: string): Promise<Quota> {
  const row = await env.DB.prepare(
    `SELECT u.drive_quota_mb AS user_mb, u.drive_bytes AS used,
       (SELECT MAX(d.drive_quota_mb) FROM domains d WHERE d.drive_enabled=1 AND d.id IN
         (SELECT mb.domain_id FROM grants g JOIN mailboxes mb ON mb.id=g.mailbox_id WHERE g.user_id=u.id)) AS dom_mb
     FROM users u WHERE u.id=?1`
  ).bind(userId).first<any>();
  const enabled = !!row && row.dom_mb != null;
  const mb = Math.min(row?.user_mb ?? row?.dom_mb ?? 0, DRIVE_HARD_CAP_MB);
  return { enabled, quota: mb * MB, used: row?.used || 0 };
}

/** Room for `add` more bytes in the owner's drive -- the owner's, not the uploader's: files created
 *  in a shared folder are charged to the folder owner.
 *  校验所有者还装得下 add 字节 —— 是所有者、不是操作者:传进共享文件夹的文件记在文件夹所有者的配额上。 */
async function checkQuota(env: Env, ownerId: string, add: number): Promise<void> {
  const q = await driveQuota(env, ownerId);
  if (!q.enabled) throw new HttpError(403, 'e_drive_disabled');
  if (q.used + add > q.quota) throw new HttpError(413, 'e_drive_quota');
}

// ---------- Tree and permission helpers ----------
// ---------- 目录树与权限 ----------

/** A folder's address: its ancestors and itself, root first. The Drive root is not in it -- it
 *  has no row, and every path implicitly starts there.
 *  一个文件夹的地址:自根而下的祖先加它自己。网盘根不在其中 —— 它没有行,而每条路径都从那里起步。 */
type FolderPath = { id: string; name: string }[];

/** The node and all its ancestors, node first, root last. Empty when the id does not exist.
 *  节点及其全部祖先,节点在前、根在后。id 不存在时为空。 */
async function chainOf(env: Env, nodeId: string): Promise<NodeRow[]> {
  const rows = await env.DB.prepare(
    `WITH RECURSIVE chain AS (
       SELECT n.*, 0 AS depth FROM drive_nodes n WHERE n.id=?1
       UNION ALL
       SELECT p.*, c.depth+1 FROM drive_nodes p JOIN chain c ON p.id=c.parent_id WHERE c.depth<${DEPTH_MAX}
     ) SELECT * FROM chain ORDER BY depth`
  ).bind(nodeId).all();
  return (rows.results || []) as unknown as NodeRow[];
}

interface Access {
  node: NodeRow;
  level: 'owner' | 'editor' | 'viewer';
  /** For share members, the highest shared ancestor -- their movements stay inside this subtree.
   *  共享成员可见范围的顶点 —— 他们的一切操作都被圈在这棵子树里。 */
  shareRoot: string | null;
  chain: NodeRow[];
}

/** Resolve what the current user may do with a node. Owners always pass (even in the trash);
 *  others need a share membership on some ancestor, and anything inside the owner's trash is
 *  invisible to them. Missing and forbidden both answer 404, to not leak existence.
 *  解析当前用户对节点的权限。所有者永远放行(含回收站);其他人需要在某个祖先上有共享成员资格,
 *  且所有者回收站里的内容对他们一律不可见。不存在与无权限统一回 404,不泄露存在性。 */
async function accessNode(c: any, nodeId: string, need: 'view' | 'edit' | 'owner'): Promise<Access> {
  const user: User = c.get('user');
  const chain = await chainOf(c.env, nodeId);
  if (!chain.length) throw new HttpError(404, 'e_drive_not_found');
  const node = chain[0];
  if (node.owner_id === user.id) return { node, level: 'owner', shareRoot: null, chain };
  if (need === 'owner') throw new HttpError(404, 'e_drive_not_found');
  if (chain.some((n) => n.trashed)) throw new HttpError(404, 'e_drive_not_found');
  const ids = chain.map((n) => n.id);
  // A share qualifies only if it is alive (not revoked, not expired), this user has actually
  // joined it, and -- when it names a domain -- they hold a mailbox under that domain. The
  // domain test is the department check: membership follows the mailbox, so someone who joins
  // the department later gains access without the share being touched.
  //
  // Public shares reach this query too, but only through a membership row, which exists solely
  // because a signed-in visitor pressed "add to my drive" on the landing page. The link itself
  // still needs no account and grants nothing here; and whatever the row says, a public share
  // is read-only -- the role is pinned at creation, refused on update, and pinned again below
  // so a single wrong row could never hand out write access.
  //
  // 一条共享要生效,必须仍然活着(未撤销、未过期)、本用户确实加入过它,并且 —— 若它指定了
  // 域名 —— 他在该域名下持有信箱。这个域名判定就是部门校验:资格随信箱走,
  // 后来加入该部门的人无需改动共享即可获得访问权。
  //
  // 公开分享也会走到这条查询,但只能经由一条成员记录进来,而那条记录的唯一来源是某个已登录
  // 的访问者在落地页上按了"添加到我的网盘"。链接本身仍然无需账号,且在此不授予任何东西;
  // 并且无论那行怎么写,公开分享一律只读 —— 角色在创建时钉死、更新时被拒,下面再钉一次,
  // 单独一行写错也绝无可能发出写权限。
  const rows = await c.env.DB.prepare(
    `SELECT si.node_id,
            CASE WHEN s.audience='public' THEN 'viewer' ELSE s.role END AS role
       FROM drive_shares s
       JOIN drive_share_items si ON si.share_id = s.id
       JOIN drive_share_members m ON m.share_id = s.id
     WHERE m.user_id=?1 AND s.audience IN ('internal','public')
       AND s.revoked_at IS NULL AND (s.expires_at IS NULL OR s.expires_at > ?2)
       AND (s.domain_id IS NULL OR EXISTS (
         SELECT 1 FROM grants g JOIN mailboxes mb ON mb.id=g.mailbox_id
          WHERE g.user_id=?1 AND mb.domain_id = s.domain_id))
       AND si.node_id IN (${ids.map((_, i) => '?' + (i + 3)).join(',')})`
  ).bind(user.id, now(), ...ids).all();
  const hits = (rows.results || []) as { node_id: string; role: string }[];
  if (!hits.length) throw new HttpError(404, 'e_drive_not_found');
  const level = hits.some((h) => h.role === 'editor') ? 'editor' : 'viewer';
  if (need === 'edit' && level !== 'editor') throw new HttpError(403, 'e_drive_forbidden');
  // Among qualifying shares pick the one closest to the root: the widest subtree
  // 命中多个共享时取离根最近的那个:活动范围最大
  const best = hits
    .filter((h) => level === 'viewer' || h.role === 'editor')
    .sort((a, b) => ids.indexOf(b.node_id) - ids.indexOf(a.node_id))[0];
  return { node, level, shareRoot: best.node_id, chain };
}

function cleanName(v: unknown): string {
  // Control characters and '/' out; everything else (any script) is welcome
  // 去掉控制字符与 '/',其余(任意文字)都放行
  const s = String(v ?? '').replace(/[\u0000-\u001f\u007f/]/g, '').trim();
  if (!s || s.length > NAME_MAX) throw new HttpError(400, 'e_drive_bad_name');
  return s;
}

function cleanMime(v: unknown): string {
  const s = String(v ?? '').toLowerCase().split(';')[0].trim();
  return /^[a-z0-9.+-]+\/[a-z0-9.+-]+$/.test(s) ? s.slice(0, 120) : 'application/octet-stream';
}

function nodeJson(n: any, withShared = true) {
  return {
    id: n.id, parent_id: n.parent_id || null, kind: n.kind, name: n.name, mime: n.mime || '',
    size: n.size || 0, tree_bytes: n.tree_bytes || 0, starred: !!n.starred, trashed: !!n.trashed,
    shared: withShared ? !!n.shared : false, thumb: !!n.has_thumb,
    created_at: n.created_at, updated_at: n.updated_at,
  };
}

/** Ancestor-chain rollup for the materialised folder sizes: one statement, O(depth) rows.
 *  Deltas are plain commutative increments, so any interleaving of concurrent operations
 *  lands on the same totals. Propagation stops at a trashed ancestor: everything above it
 *  already dropped that subtree's contribution when the ancestor was trashed (matters when a
 *  node inside a trashed folder is trashed individually via the API). Returns null when there
 *  is nothing to do.
 *  物化文件夹大小的祖先链上卷。一条语句,O(深度) 行。增量是可交换的加法,并发操作任意交错
 *  结果都一致。传播在已回收祖先处停止:其上层早在该祖先进回收站时就扣掉了整棵子树的贡献
 *  (对"经 API 单独回收已回收文件夹内的节点"这种路径至关重要)。无事可做时返回 null。 */
function ancDelta(env: Env, parentId: string | null | undefined, delta: number): D1PreparedStatement | null {
  if (!parentId || !delta) return null;
  return env.DB.prepare(
    `WITH RECURSIVE anc(id, depth) AS (
       SELECT ?1, 0
       UNION ALL SELECT n.parent_id, a.depth+1 FROM drive_nodes n JOIN anc a ON n.id=a.id
       WHERE n.parent_id IS NOT NULL AND n.trashed=0 AND a.depth<${DEPTH_MAX}
     ) UPDATE drive_nodes SET tree_bytes=MAX(tree_bytes+?2,0) WHERE kind='folder' AND id IN (SELECT id FROM anc)`
  ).bind(parentId, delta);
}

/** The bytes a node contributes to its ancestors: its own size, or its materialised subtree
 *  本节点为祖先贡献的字节数:文件是自身大小,文件夹是其物化子树大小 */
const nodeBytes = (n: NodeRow | any): number => (n.kind === 'file' ? n.size || 0 : n.tree_bytes || 0);

/** Where a create/upload lands: the user's own root, or a folder they can edit (their own or a
 *  shared one -- then the folder owner's drive takes the file). Nothing lands inside a trash.
 *  新建/上传落到哪里:自己的根目录,或一个有编辑权的文件夹(自己的或共享的 —— 后者落入文件夹
 *  所有者的网盘)。回收站里不允许落任何东西。 */
async function resolveWriteTarget(c: any, parent: string): Promise<{ ownerId: string; parentId: string | null }> {
  if (parent === 'root' || !parent) return { ownerId: (c.get('user') as User).id, parentId: null };
  const a = await accessNode(c, parent, 'edit');
  if (a.node.kind !== 'folder') throw new HttpError(400, 'e_drive_not_folder');
  if (a.chain.some((n) => n.trashed)) throw new HttpError(400, 'e_drive_trashed');
  if (a.chain.length >= DEPTH_MAX - 1) throw new HttpError(400, 'e_drive_too_deep');
  return { ownerId: a.node.owner_id, parentId: a.node.id };
}

/** The Drive forbids duplicate names per folder and kind. This finds the standing occupant of a
 *  name so uploads can overwrite it and renames can refuse it. Ranked newest-first because
 *  legacy data may still hold duplicates from before the rule.
 *  网盘按目录和类型禁止重名。此函数找出当前占着某个名字的节点。上传用它来覆盖,
 *  改名用它来拒绝。按最新排序,因为规则之前的存量数据可能已有重名。 */
async function findClash(env: Env, ownerId: string, parentId: string | null, name: string, kind: string): Promise<NodeRow | null> {
  const sql = parentId
    ? 'SELECT * FROM drive_nodes WHERE owner_id=?1 AND parent_id=?2 AND name=?3 AND kind=?4 AND trashed=0 ORDER BY updated_at DESC LIMIT 1'
    : 'SELECT * FROM drive_nodes WHERE owner_id=?1 AND parent_id IS NULL AND name=?2 AND kind=?3 AND trashed=0 ORDER BY updated_at DESC LIMIT 1';
  const binds = parentId ? [ownerId, parentId, name, kind] : [ownerId, name, kind];
  const row = await env.DB.prepare(sql).bind(...binds).first();
  return (row as unknown as NodeRow) || null;
}

/** Drop rows whose ancestors include a trashed folder (used by search/starred/recent, where the
 *  query alone cannot see implicit trash membership). Chain lookups are memoised per parent.
 *  Pass `paths` to also collect each folder's root-first name path: the chains are already being
 *  fetched for the trash check, so the addresses cost nothing beyond the copying.
 *  过滤掉祖先在回收站里的行(搜索/星标/最近用 —— 单条查询看不出"隐式在回收站")。按父节点缓存。
 *  传入 `paths` 可顺带收集每个文件夹自根而下的名字路径:祖先链本来就为回收站检查取过了,
 *  这些地址除了拷贝之外不多花任何代价。 */
async function dropTrashedAncestors(env: Env, rows: any[], paths?: Map<string, FolderPath>): Promise<any[]> {
  const bad = new Map<string, boolean>();
  const out: any[] = [];
  for (const r of rows) {
    if (r.trashed) continue;
    if (!r.parent_id) { out.push(r); continue; }
    if (!bad.has(r.parent_id)) {
      const chain = await chainOf(env, r.parent_id);
      let b = !chain.length;
      // The chain arrives node-first; walking it backwards is walking down from the root, which
      // is both the order the trash flag propagates and the order a path is read.
      // 链是"节点在前"送来的;倒着走就是自根而下 —— 既是回收站标记传播的方向,也是路径读出来的顺序。
      const acc: FolderPath = [];
      for (let i = chain.length - 1; i >= 0; i--) {
        b = b || !!chain[i].trashed;
        bad.set(chain[i].id, b);
        if (paths) {
          acc.push({ id: chain[i].id, name: chain[i].name });
          paths.set(chain[i].id, [...acc]);
        }
      }
      if (!chain.length) bad.set(r.parent_id, true);
    }
    if (!bad.get(r.parent_id)) out.push(r);
  }
  return out;
}

/** Permanently delete up to `limit` nodes of the subtree at rootId, deepest first (children always
 *  go before their parent, so an interrupted run leaves a consistent tree). Removes R2 objects,
 *  share rows and refunds the owner's quota. Returns how many nodes remain.
 *  彻底删除以 rootId 为根的子树,一次最多 limit 个节点、最深的先删(孩子永远先于父亲,中断后树仍
 *  一致)。连带删 R2 对象与共享记录,并退还所有者配额。返回还剩多少节点。 */
export async function purgeSubtree(env: Env, rootId: string, limit = PURGE_BATCH): Promise<number> {
  const rows = await env.DB.prepare(
    `WITH RECURSIVE sub(id, depth) AS (
       SELECT id, 0 FROM drive_nodes WHERE id=?1
       UNION ALL SELECT n.id, s.depth+1 FROM drive_nodes n JOIN sub s ON n.parent_id=s.id WHERE s.depth<${DEPTH_MAX}
     ) SELECT n.id, n.kind, n.size, n.r2_key, n.owner_id FROM sub JOIN drive_nodes n ON n.id=sub.id
     ORDER BY sub.depth DESC`
  ).bind(rootId).all();
  const all = (rows.results || []) as any[];
  if (!all.length) return 0;
  const batch = all.slice(0, limit);
  // Each file may carry a thumbnail at <r2_key>.t -- delete it in the same sweep.
  // R2 bulk delete silently skips keys that do not exist.
  // 每个文件旁可能有 <r2_key>.t 的缩略图,同一批顺手删掉。R2 批量删除对不存在的键静默跳过。
  const keys = batch.flatMap((n) => (n.r2_key ? [n.r2_key, n.r2_key + THUMB_SUFFIX] : []));
  for (let i = 0; i < keys.length; i += 900) {
    await env.RAW.delete(keys.slice(i, i + 900)).catch(() => {});
  }
  const freed = batch.reduce((s, n) => s + (n.kind === 'file' ? n.size || 0 : 0), 0);
  const stmts: D1PreparedStatement[] = [];
  for (let i = 0; i < batch.length; i += 90) {
    const part = batch.slice(i, i + 90).map((n) => n.id);
    const ph = part.map((_, j) => '?' + (j + 1)).join(',');
    // Drop these nodes from every share they appear in. The share itself survives: it may well
    // hold other items, and one of them being deleted is not a reason to kill the link. A share
    // left with nothing is reported as empty by shareItems() and simply serves no content.
    // 把这些节点从所有包含它们的共享中摘掉。共享本身保留:它很可能还含别的条目,
    // 其中一个被删不构成销毁链接的理由。条目全空的共享由 shareItems() 报告为空,供不出内容而已。
    stmts.push(env.DB.prepare(`DELETE FROM drive_share_items WHERE node_id IN (${ph})`).bind(...part));
    stmts.push(env.DB.prepare(`DELETE FROM drive_nodes WHERE id IN (${ph})`).bind(...part));
  }
  if (freed > 0) {
    stmts.push(env.DB.prepare('UPDATE users SET drive_bytes=MAX(drive_bytes-?1,0) WHERE id=?2').bind(freed, batch[0].owner_id));
  }
  await env.DB.batch(stmts);
  return all.length - batch.length;
}

// ---------- User-facing API (/api/drive) ----------
// ---------- 用户侧 API(/api/drive) ----------

export const driveApp = new Hono<Ctx>();

// In-isolate short-lived caches for the media streaming hot path. A video seek fires a fresh
// Range request, and each one was paying two to three SEQUENTIAL D1 round trips (quota gate,
// ancestor-chain access CTE, share membership) before R2 produced a single byte. Worker
// isolates live across requests, so a 60-second memory cache absorbs the burst that scrubbing
// the timeline generates. Scope: read-only file streaming; everything that mutates or displays
// live numbers keeps querying fresh. Revoking a share can lag a playing stream by up to 60s;
// deletes do not (R2 is already empty and answers 404).
// 流媒体热路径的 isolate 内存短时缓存。每次视频 seek 都是一个新的 Range 请求,
// 之前每个都要串行付 2-3 个 D1 往返(配额闸、祖先链权限 CTE、共享成员)之后 R2 才出第一个字节。
// Worker isolate 跨请求存活,60 秒的内存缓存正好吸收拖进度条产生的这阵请求风暴。
// 只作用于只读的文件流。所有写操作与实时数字仍然现查。撤销共享对正在播的流最多延迟 60 秒;
// 删除不受此影响(R2 已空,直接 404)。
const STREAM_TTL = 60 * 1000;
const quotaCache = new Map<string, { q: Quota; exp: number }>();
const accessCache = new Map<string, { node: NodeRow; exp: number }>();
const sweep = (m: Map<string, unknown>) => {
  if (m.size > 500) m.clear();
};

const isStreamRead = (c: any) => c.req.method === 'GET' && String(c.req.path || '').includes('/files/');

driveApp.use('*', requireAuth);
driveApp.use('*', async (c, next) => {
  const uid2 = c.get('user').id;
  let q: Quota | null = null;
  if (isStreamRead(c)) {
    const hit = quotaCache.get(uid2);
    if (hit && hit.exp > Date.now()) q = hit.q;
  }
  if (!q) {
    q = await driveQuota(c.env, uid2);
    sweep(quotaCache);
    quotaCache.set(uid2, { q, exp: Date.now() + STREAM_TTL });
  }
  if (!q.enabled) throw new HttpError(403, 'e_drive_disabled');
  c.set('dq', q);
  await next();
});

/** View access for streaming endpoints, memoised per (user, node) for 60 seconds
 *  流端点的读权限。按用户与节点记忆 60 秒 */
async function accessFileCached(c: any, nodeId: string): Promise<NodeRow> {
  const key = (c.get('user') as User).id + ':' + nodeId;
  const hit = accessCache.get(key);
  if (hit && hit.exp > Date.now()) return hit.node;
  const a = await accessNode(c, nodeId, 'view');
  sweep(accessCache);
  accessCache.set(key, { node: a.node, exp: Date.now() + STREAM_TTL });
  return a.node;
}

driveApp.get('/state', (c) => {
  const q = c.get('dq');
  return c.json({ used: q.used, quota: q.quota, single_max: SINGLE_MAX, part_size: PART_SIZE, trash_days: 30 });
});

driveApp.get('/list', async (c) => {
  const parent = String(c.req.query('parent') || 'root');
  const user = c.get('user');
  const childrenSql = (where: string) =>
    `SELECT n.*, (SELECT 1 FROM drive_share_items si JOIN drive_shares s ON s.id=si.share_id WHERE si.node_id=n.id AND s.revoked_at IS NULL) AS shared
     FROM drive_nodes n WHERE ${where} AND n.trashed=0
     ORDER BY n.kind='folder' DESC, n.name COLLATE NOCASE LIMIT ${LIST_LIMIT}`;
  if (parent === 'root') {
    const rows = await c.env.DB.prepare(childrenSql('n.owner_id=?1 AND n.parent_id IS NULL')).bind(user.id).all();
    return c.json({
      access: 'owner', share_root: null, path: [],
      nodes: (rows.results || []).map((n) => nodeJson(n)),
    });
  }
  const a = await accessNode(c, parent, 'view');
  if (a.node.kind !== 'folder') throw new HttpError(400, 'e_drive_not_folder');
  const rows = await c.env.DB.prepare(childrenSql('n.parent_id=?1')).bind(a.node.id).all();
  // Breadcrumbs: the owner sees the full path; a share member's path stops at the share root
  // 面包屑:所有者看全路径;共享成员只能看到共享顶点以下
  let path = a.chain.slice().reverse();
  if (a.shareRoot) path = path.slice(path.findIndex((n) => n.id === a.shareRoot));
  return c.json({
    access: a.level, share_root: a.shareRoot,
    // Owners may browse folders that sit in the trash; the UI switches to trash-style actions
    // 所有者可以浏览回收站里的文件夹;界面据此切换成回收站式的操作
    in_trash: a.chain.some((n) => n.trashed),
    path: path.map((n) => ({ id: n.id, name: n.name })),
    nodes: (rows.results || []).map((n) => nodeJson(n, a.level === 'owner')),
  });
});

/** Node metadata with its breadcrumb path (share-trimmed) -- deep links into an archive
 *  rebuild the path bar from this.
 *  节点元数据及面包屑路径(按共享裁剪)。压缩包深链靠它重建路径条。 */
driveApp.get('/nodes/:id/meta', async (c) => {
  const a = await accessNode(c, c.req.param('id'), 'view');
  let path = a.chain.slice(1).reverse();
  if (a.shareRoot) {
    const i = path.findIndex((n) => n.id === a.shareRoot);
    path = i >= 0 ? path.slice(i) : [];
  }
  return c.json({
    node: nodeJson(a.node, a.level === 'owner'),
    access: a.level,
    path: path.map((n) => ({ id: n.id, name: n.name })),
  });
});

driveApp.get('/search', async (c) => {
  const q = String(c.req.query('q') || '').trim().slice(0, 100);
  if (!q) return c.json({ nodes: [] });
  const like = '%' + q.replace(/[\\%_]/g, (ch) => '\\' + ch) + '%';
  const rows = await c.env.DB.prepare(
    `SELECT n.*, (SELECT 1 FROM drive_share_items si JOIN drive_shares s ON s.id=si.share_id WHERE si.node_id=n.id AND s.revoked_at IS NULL) AS shared FROM drive_nodes n
     WHERE n.owner_id=?1 AND n.trashed=0 AND n.name LIKE ?2 ESCAPE '\\'
     ORDER BY n.updated_at DESC LIMIT 200`
  ).bind(c.get('user').id, like).all();
  // Hits scatter across the whole drive, so each one has to say where it lives. The addresses
  // travel once per folder rather than once per hit -- a query that matches thirty files in the
  // same folder repeats that folder's path thirty times otherwise.
  // 命中散落在整个网盘里,所以每一条都得说清自己住在哪。地址按文件夹发一次,而不是按命中发一次 ——
  // 否则一次命中同一文件夹三十个文件的搜索,就要把那个文件夹的路径重复三十遍。
  const paths = new Map<string, FolderPath>();
  const vis = await dropTrashedAncestors(c.env, rows.results || [], paths);
  const folders: Record<string, FolderPath> = {};
  for (const n of vis) if (n.parent_id && paths.has(n.parent_id)) folders[n.parent_id] = paths.get(n.parent_id)!;
  return c.json({ nodes: vis.map((n) => nodeJson(n)), folders });
});

driveApp.get('/starred', async (c) => {
  const rows = await c.env.DB.prepare(
    `SELECT n.*, (SELECT 1 FROM drive_share_items si JOIN drive_shares s ON s.id=si.share_id WHERE si.node_id=n.id AND s.revoked_at IS NULL) AS shared FROM drive_nodes n
     WHERE n.owner_id=?1 AND n.starred=1 AND n.trashed=0
     ORDER BY n.kind='folder' DESC, n.name COLLATE NOCASE LIMIT ${LIST_LIMIT}`
  ).bind(c.get('user').id).all();
  const vis = await dropTrashedAncestors(c.env, rows.results || []);
  return c.json({ nodes: vis.map((n) => nodeJson(n)) });
});

driveApp.get('/recent', async (c) => {
  const rows = await c.env.DB.prepare(
    `SELECT n.*, (SELECT 1 FROM drive_share_items si JOIN drive_shares s ON s.id=si.share_id WHERE si.node_id=n.id AND s.revoked_at IS NULL) AS shared FROM drive_nodes n
     WHERE n.owner_id=?1 AND n.kind='file' AND n.trashed=0 ORDER BY n.updated_at DESC LIMIT 80`
  ).bind(c.get('user').id).all();
  const vis = (await dropTrashedAncestors(c.env, rows.results || [])).slice(0, 50);
  return c.json({ nodes: vis.map((n) => nodeJson(n)) });
});

driveApp.get('/trash', async (c) => {
  const rows = await c.env.DB.prepare(
    `SELECT * FROM drive_nodes WHERE owner_id=?1 AND trashed=1 ORDER BY trashed_at DESC LIMIT ${LIST_LIMIT}`
  ).bind(c.get('user').id).all();
  return c.json({ nodes: (rows.results || []).map((n) => nodeJson(n, false)) });
});

driveApp.post('/folders', async (c) => {
  const body = await c.req.json<any>();
  const name = cleanName(body.name);
  const target = await resolveWriteTarget(c, String(body.parent || 'root'));
  // No duplicate names: an existing folder of the same name IS the result (merge semantics --
  // re-uploading a directory lands in the same tree instead of minting a twin)
  // 禁止重名。已有同名文件夹就直接作为结果返回(合并语义 —— 目录重传落回同一棵树,
  // 不再造出双胞胎)
  const clash = await findClash(c.env, target.ownerId, target.parentId, name, 'folder');
  if (clash) return c.json(nodeJson(clash));
  const id = uid();
  const t = now();
  await c.env.DB.prepare(
    `INSERT INTO drive_nodes (id, owner_id, parent_id, kind, name, created_at, updated_at) VALUES (?1,?2,?3,'folder',?4,?5,?5)`
  ).bind(id, target.ownerId, target.parentId, name, t).run();
  return c.json(nodeJson({ id, parent_id: target.parentId, kind: 'folder', name, created_at: t, updated_at: t }));
});

driveApp.post('/nodes/:id/rename', async (c) => {
  const a = await accessNode(c, c.req.param('id'), 'edit');
  if (a.chain.some((n) => n.trashed)) throw new HttpError(400, 'e_drive_trashed');
  if (a.level !== 'owner' && a.node.id === a.shareRoot) throw new HttpError(403, 'e_drive_forbidden');
  const name = cleanName((await c.req.json<any>()).name);
  // Renaming onto an occupied name is refused -- overwrite semantics belong to uploads only
  // 改名撞上已占用的名字直接拒绝。覆盖语义只属于上传
  const clash = await findClash(c.env, a.node.owner_id, a.node.parent_id, name, a.node.kind);
  if (clash && clash.id !== a.node.id) throw new HttpError(409, 'e_drive_name_taken');
  await c.env.DB.prepare('UPDATE drive_nodes SET name=?1, updated_at=?2 WHERE id=?3').bind(name, now(), a.node.id).run();
  return c.json({ ok: true, name });
});

driveApp.post('/nodes/:id/star', async (c) => {
  const a = await accessNode(c, c.req.param('id'), 'owner');
  const on = (await c.req.json<any>()).starred ? 1 : 0;
  await c.env.DB.prepare('UPDATE drive_nodes SET starred=?1 WHERE id=?2').bind(on, a.node.id).run();
  return c.json({ ok: true, starred: !!on });
});

driveApp.post('/nodes/:id/move', async (c) => {
  const a = await accessNode(c, c.req.param('id'), 'edit');
  if (a.chain.some((n) => n.trashed)) throw new HttpError(400, 'e_drive_trashed');
  if (a.level !== 'owner' && a.node.id === a.shareRoot) throw new HttpError(403, 'e_drive_forbidden');
  const parent = String((await c.req.json<any>()).parent || 'root');
  let parentId: string | null;
  if (parent === 'root') {
    // Only the owner has a root here; an editor's own root is a different drive
    // 根目录只属于所有者;编辑者的根是另一个人的网盘
    if (a.level !== 'owner') throw new HttpError(403, 'e_drive_forbidden');
    parentId = null;
  } else {
    const t = await accessNode(c, parent, 'edit');
    if (t.node.kind !== 'folder') throw new HttpError(400, 'e_drive_not_folder');
    if (t.chain.some((n) => n.trashed)) throw new HttpError(400, 'e_drive_trashed');
    // No ownership transfer: source and target must live in the same drive
    // 不做所有权转移:源与目标必须在同一个人的网盘里
    if (t.node.owner_id !== a.node.owner_id) throw new HttpError(400, 'e_drive_cross_drive');
    if (t.chain.some((n) => n.id === a.node.id)) throw new HttpError(400, 'e_drive_cycle');
    if (t.chain.length + 1 >= DEPTH_MAX) throw new HttpError(400, 'e_drive_too_deep');
    parentId = t.node.id;
  }
  // The destination must not already hold this name / 目的地不能已有同名条目
  const clash = await findClash(c.env, a.node.owner_id, parentId, a.node.name, a.node.kind);
  if (clash && clash.id !== a.node.id) throw new HttpError(409, 'e_drive_name_taken');
  {
    const stmts = [
      c.env.DB.prepare('UPDATE drive_nodes SET parent_id=?1, updated_at=?2 WHERE id=?3')
        .bind(parentId, now(), a.node.id),
    ];
    // Old chain loses the bytes, new chain gains them; a shared prefix nets to zero by itself
    // 旧链减、新链加。公共前缀一减一加自动归零,无需特判
    if (parentId !== a.node.parent_id) {
      const bytes = nodeBytes(a.node);
      const sub = ancDelta(c.env, a.node.parent_id, -bytes);
      const add = ancDelta(c.env, parentId, bytes);
      if (sub) stmts.push(sub);
      if (add) stmts.push(add);
    }
    await c.env.DB.batch(stmts);
  }
  return c.json({ ok: true });
});

driveApp.post('/nodes/:id/trash', async (c) => {
  const a = await accessNode(c, c.req.param('id'), 'edit');
  if (a.level !== 'owner' && a.node.id === a.shareRoot) throw new HttpError(403, 'e_drive_forbidden');
  if (!a.node.trashed) {
    const t = now();
    const stmts = [
      c.env.DB.prepare('UPDATE drive_nodes SET trashed=1, trashed_at=?1, updated_at=?1 WHERE id=?2')
        .bind(t, a.node.id),
    ];
    // A folder's own tree_bytes IS its contribution -- no recursive sum ever needed
    // 文件夹自己的 tree_bytes 就是它的贡献量,永远不用递归求和
    const ad = ancDelta(c.env, a.node.parent_id, -nodeBytes(a.node));
    if (ad) stmts.push(ad);
    await c.env.DB.batch(stmts);
  }
  return c.json({ ok: true });
});

driveApp.post('/nodes/:id/restore', async (c) => {
  const a = await accessNode(c, c.req.param('id'), 'owner');
  if (!a.node.trashed) throw new HttpError(400, 'e_drive_not_trashed');
  // If the original spot is gone or itself in the trash, restore to the root instead
  // 原位置没了或也在回收站里,就还原到根目录
  let parentId = a.node.parent_id;
  if (parentId) {
    const chain = await chainOf(c.env, parentId);
    if (!chain.length || chain.some((n) => n.trashed)) parentId = null;
  }
  {
    const stmts = [
      c.env.DB.prepare('UPDATE drive_nodes SET trashed=0, trashed_at=NULL, parent_id=?1, updated_at=?2 WHERE id=?3')
        .bind(parentId, now(), a.node.id),
    ];
    const ad = ancDelta(c.env, parentId, nodeBytes(a.node));
    if (ad) stmts.push(ad);
    await c.env.DB.batch(stmts);
  }
  return c.json({ ok: true });
});

driveApp.delete('/nodes/:id', async (c) => {
  const a = await accessNode(c, c.req.param('id'), 'owner');
  if (!a.node.trashed) throw new HttpError(400, 'e_drive_not_trashed');
  const remaining = await purgeSubtree(c.env, a.node.id);
  return c.json({ remaining });
});

driveApp.post('/trash/empty', async (c) => {
  const user = c.get('user');
  const row = await c.env.DB.prepare(
    'SELECT id FROM drive_nodes WHERE owner_id=?1 AND trashed=1 LIMIT 1'
  ).bind(user.id).first<any>();
  if (row) await purgeSubtree(c.env, row.id);
  const left = await c.env.DB.prepare(
    'SELECT COUNT(*) AS n FROM drive_nodes WHERE owner_id=?1 AND trashed=1'
  ).bind(user.id).first<any>();
  return c.json({ remaining: left?.n || 0 });
});

// ---------- Upload ----------
// ---------- 上传 ----------

// Small files in one request: raw body, metadata in the query string
// 小文件一次请求:原始字节做 body,元数据放查询串
driveApp.post('/upload', async (c) => {
  // `node` targets an existing file directly: the caller needs edit rights on THAT FILE, not on
  // the folder holding it. That is what makes a single shared file updatable -- its recipient
  // was given the file, never the folder, so they have nowhere to "upload a file of the same
  // name" into. The name and location are fixed by the target; only the bytes change.
  // `node` 直接指向一个已有文件:调用者需要的是对"该文件"的编辑权,而不是对其所在目录的。
  // 正是这一点让"单独分享的文件"可被更新 —— 接收方拿到的是文件而非目录,
  // 他没有任何地方可以"上传一个同名文件"。名称与位置由目标锁定,变的只有内容。
  const overwriteId = String(c.req.query('node') || '');
  let target: { ownerId: string; parentId: string | null };
  let name: string;
  let clash: NodeRow | null;
  if (overwriteId) {
    const a = await accessNode(c, overwriteId, 'edit');
    if (a.node.kind !== 'file') throw new HttpError(400, 'e_drive_not_file');
    if (a.chain.some((n) => n.trashed)) throw new HttpError(400, 'e_drive_trashed');
    target = { ownerId: a.node.owner_id, parentId: a.node.parent_id };
    name = a.node.name;
    clash = a.node;
  } else {
    target = await resolveWriteTarget(c, String(c.req.query('parent') || 'root'));
    name = cleanName(c.req.query('name'));
    // An occupied name means overwrite: same node id, same R2 key, new bytes. The put below
    // replaces the object atomically; star and creation date simply stay.
    // 名字被占用即覆盖。同一节点 id、同一 R2 键、换新字节。下面的 put 原子替换对象,
    // 星标与创建时间自然保留。
    clash = await findClash(c.env, target.ownerId, target.parentId, name, 'file');
  }
  const mime = cleanMime(c.req.query('mime'));
  const len = parseInt(c.req.header('Content-Length') || '', 10);
  if (!c.req.raw.body || !Number.isFinite(len) || len < 0) throw new HttpError(400, 'e_drive_body_required');
  if (len > SINGLE_MAX) throw new HttpError(413, 'e_drive_part_too_big');
  const oldSize = clash?.size || 0;
  const q0 = await driveQuota(c.env, target.ownerId);
  if (!q0.enabled) throw new HttpError(403, 'e_drive_disabled');
  if (q0.used - oldSize + len > q0.quota) throw new HttpError(413, 'e_drive_quota');
  const id = clash ? clash.id : uid();
  const key = clash?.r2_key || `drive/${target.ownerId}/${id}`;
  const obj = await c.env.RAW.put(key, c.req.raw.body, { httpMetadata: { contentType: mime } });
  const size = obj?.size ?? len;
  const t = now();
  if (clash) {
    // The stale thumbnail dies with the old bytes / 旧缩略图随旧内容一起作废
    await c.env.RAW.delete(key + THUMB_SUFFIX).catch(() => {});
    const stmts = [
      c.env.DB.prepare('UPDATE drive_nodes SET mime=?1, size=?2, has_thumb=0, updated_at=?3 WHERE id=?4')
        .bind(mime, size, t, id),
      c.env.DB.prepare('UPDATE users SET drive_bytes=MAX(drive_bytes+?1,0) WHERE id=?2')
        .bind(size - oldSize, target.ownerId),
    ];
    const ad = ancDelta(c.env, target.parentId, size - oldSize);
    if (ad) stmts.push(ad);
    await c.env.DB.batch(stmts);
    return c.json(nodeJson({ ...clash, mime, size, has_thumb: 0, updated_at: t, tree_bytes: clash.tree_bytes }));
  }
  // Re-check with the actual byte count; concurrent uploads may both have passed the pre-check
  // 用实际字节数复核一次;并发上传可能都通过了预检
  const q = await driveQuota(c.env, target.ownerId);
  if (q.used + size > q.quota) {
    await c.env.RAW.delete(key).catch(() => {});
    throw new HttpError(413, 'e_drive_quota');
  }
  {
    const stmts = [
      c.env.DB.prepare(
        `INSERT INTO drive_nodes (id, owner_id, parent_id, kind, name, mime, size, r2_key, created_at, updated_at)
         VALUES (?1,?2,?3,'file',?4,?5,?6,?7,?8,?8)`
      ).bind(id, target.ownerId, target.parentId, name, mime, size, key, t),
      c.env.DB.prepare('UPDATE users SET drive_bytes=drive_bytes+?1 WHERE id=?2').bind(size, target.ownerId),
    ];
    const ad = ancDelta(c.env, target.parentId, size);
    if (ad) stmts.push(ad);
    await c.env.DB.batch(stmts);
  }
  return c.json(nodeJson({ id, parent_id: target.parentId, kind: 'file', name, mime, size, created_at: t, updated_at: t }));
});

// Large files go through R2 multipart. The server keeps the declared size and target on its own
// authority (drive_uploads) instead of trusting the complete call; stale rows are aborted hourly.
// 大文件走 R2 分片。声明的大小与落点由服务端自己记(drive_uploads),不信 complete 请求;
// 过期未完成的由小时级 cron 中止。
driveApp.post('/upload/init', async (c) => {
  const body = await c.req.json<any>();
  const target = await resolveWriteTarget(c, String(body.parent || 'root'));
  const name = cleanName(body.name);
  const mime = cleanMime(body.mime);
  const size = Math.floor(Number(body.size));
  if (!Number.isFinite(size) || size <= 0) throw new HttpError(400, 'e_drive_body_required');
  await checkQuota(c.env, target.ownerId, size);
  const id = uid();
  const key = `drive/${target.ownerId}/${id}`;
  const mp = await c.env.RAW.createMultipartUpload(key, { httpMetadata: { contentType: mime } });
  await c.env.DB.prepare(
    `INSERT INTO drive_uploads (id, user_id, owner_id, parent_id, name, mime, size, r2_key, upload_id, created_at)
     VALUES (?1,?2,?3,?4,?5,?6,?7,?8,?9,?10)`
  ).bind(id, c.get('user').id, target.ownerId, target.parentId, name, mime, size, key, mp.uploadId, now()).run();
  return c.json({ id, part_size: PART_SIZE });
});

async function getUpload(c: any): Promise<any> {
  const u = await c.env.DB.prepare('SELECT * FROM drive_uploads WHERE id=?1 AND user_id=?2')
    .bind(c.req.param('id'), (c.get('user') as User).id).first();
  if (!u) throw new HttpError(404, 'e_drive_upload_missing');
  return u;
}

driveApp.put('/upload/:id/part', async (c) => {
  const u = await getUpload(c);
  const n = parseInt(c.req.query('n') || '', 10);
  if (!Number.isFinite(n) || n < 1 || n > 10000) throw new HttpError(400, 'e_bad_request');
  const len = parseInt(c.req.header('Content-Length') || '', 10);
  if (!c.req.raw.body || !Number.isFinite(len) || len <= 0) throw new HttpError(400, 'e_drive_body_required');
  if (len > SINGLE_MAX) throw new HttpError(413, 'e_drive_part_too_big');
  const mpu = c.env.RAW.resumeMultipartUpload(u.r2_key, u.upload_id);
  const part = await mpu.uploadPart(n, c.req.raw.body as any);
  return c.json({ n: part.partNumber, etag: part.etag });
});

driveApp.post('/upload/:id/complete', async (c) => {
  const u = await getUpload(c);
  const body = await c.req.json<any>();
  const parts = (Array.isArray(body.parts) ? body.parts : [])
    .map((p: any) => ({ partNumber: parseInt(p.n, 10), etag: String(p.etag || '') }))
    .filter((p: any) => Number.isFinite(p.partNumber) && p.etag);
  if (!parts.length) throw new HttpError(400, 'e_bad_request');
  const mpu = c.env.RAW.resumeMultipartUpload(u.r2_key, u.upload_id);
  let obj: R2Object;
  try {
    obj = await mpu.complete(parts);
  } catch (e) {
    await mpu.abort().catch(() => {});
    await c.env.DB.prepare('DELETE FROM drive_uploads WHERE id=?1').bind(u.id).run();
    throw new HttpError(400, 'e_drive_upload_failed');
  }
  // The target folder may have been trashed or purged while the upload ran -- fall back to the root
  // 上传期间目标文件夹可能已进回收站或被删 —— 回落到根目录
  let parentId = u.parent_id;
  if (parentId) {
    const chain = await chainOf(c.env, parentId);
    if (!chain.length || chain.some((x) => x.trashed) || chain[0].owner_id !== u.owner_id || chain[0].kind !== 'folder') {
      parentId = null;
    }
  }
  // Occupied name = overwrite: the old node and its bytes go away, the new node inherits the
  // star and the creation date.
  // 名字被占用即覆盖。旧节点连同其字节移除,新节点继承星标与创建时间。
  const clash = await findClash(c.env, u.owner_id, parentId, u.name, 'file');
  const q = await driveQuota(c.env, u.owner_id);
  if (q.used - (clash?.size || 0) + obj.size > q.quota) {
    await c.env.RAW.delete(u.r2_key).catch(() => {});
    await c.env.DB.prepare('DELETE FROM drive_uploads WHERE id=?1').bind(u.id).run();
    throw new HttpError(413, 'e_drive_quota');
  }
  const t = now();
  if (clash) {
    await c.env.RAW.delete([clash.r2_key!, clash.r2_key + THUMB_SUFFIX]).catch(() => {});
  }
  const stmts = [
    ...(clash ? [c.env.DB.prepare('DELETE FROM drive_nodes WHERE id=?1').bind(clash.id)] : []),
    c.env.DB.prepare(
      `INSERT INTO drive_nodes (id, owner_id, parent_id, kind, name, mime, size, r2_key, starred, created_at, updated_at)
       VALUES (?1,?2,?3,'file',?4,?5,?6,?7,?8,?9,?10)`
    ).bind(u.id, u.owner_id, parentId, u.name, u.mime, obj.size, u.r2_key,
      clash ? clash.starred : 0, clash ? clash.created_at : t, t),
    c.env.DB.prepare('UPDATE users SET drive_bytes=MAX(drive_bytes+?1,0) WHERE id=?2')
      .bind(obj.size - (clash?.size || 0), u.owner_id),
    c.env.DB.prepare('DELETE FROM drive_uploads WHERE id=?1').bind(u.id),
  ];
  // Overwrite replaces bytes under the same parent, so one net delta covers both
  // 覆盖发生在同一父目录下,一条净增量同时涵盖旧去新来
  const ad = ancDelta(c.env, parentId, obj.size - (clash?.size || 0));
  if (ad) stmts.push(ad);
  await c.env.DB.batch(stmts);
  return c.json(nodeJson({
    id: u.id, parent_id: parentId, kind: 'file', name: u.name, mime: u.mime, size: obj.size, created_at: t, updated_at: t,
  }));
});

driveApp.post('/upload/:id/abort', async (c) => {
  const u = await getUpload(c);
  try {
    await c.env.RAW.resumeMultipartUpload(u.r2_key, u.upload_id).abort();
  } catch {}
  await c.env.DB.prepare('DELETE FROM drive_uploads WHERE id=?1').bind(u.id).run();
  return c.json({ ok: true });
});

// ---------- Download ----------
// ---------- 下载 ----------

function parseRange(h: string | undefined): any {
  if (!h) return null;
  const m = /^bytes=(\d*)-(\d*)$/.exec(h.trim());
  if (!m || (!m[1] && !m[2])) return null;
  if (!m[1]) return { suffix: parseInt(m[2], 10) };
  const offset = parseInt(m[1], 10);
  if (!m[2]) return { offset };
  const end = parseInt(m[2], 10);
  if (end < offset) return null;
  return { offset, length: end - offset + 1 };
}

driveApp.get('/files/:id/dl', async (c) => serveFile(c, await accessFileCached(c, c.req.param('id'))));

/** Stream a file node out of R2, honouring Range. Shared by the signed-in endpoint and the
 *  public share endpoint -- the two differ only in how they decided the caller may see it.
 *  从 R2 流出一个文件节点,支持 Range。登录端点与公开共享端点共用 ——
 *  两者的差别只在于"凭什么认定调用者可以看它"。 */
async function serveFile(c: any, node: NodeRow): Promise<Response> {
  if (node.kind !== 'file' || !node.r2_key) throw new HttpError(400, 'e_drive_not_file');
  const range = parseRange(c.req.header('Range'));
  const obj: any = await c.env.RAW.get(node.r2_key, range ? { range } : undefined);
  if (!obj) throw new HttpError(404, 'e_drive_not_found');
  const mime = (node.mime || '').toLowerCase();
  const inline = c.req.query('inline') === '1' && INLINE_MIMES.has(mime);
  const h = new Headers();
  h.set('X-Content-Type-Options', 'nosniff');
  h.set('Accept-Ranges', 'bytes');
  h.set('Cache-Control', 'private, max-age=3600');
  h.set('ETag', `"${node.id}-${node.updated_at}"`);
  h.set('Content-Type', inline ? (mime === 'text/plain' ? 'text/plain; charset=utf-8' : mime) : mime || 'application/octet-stream');
  h.set('Content-Disposition', `${inline ? 'inline' : 'attachment'}; filename*=UTF-8''${encodeURIComponent(node.name)}`);
  if (range) {
    const r: any = obj.range || {};
    let off = 0;
    let len = obj.size;
    if (typeof r.offset === 'number') {
      off = r.offset;
      len = typeof r.length === 'number' ? r.length : obj.size - off;
    } else if (typeof r.suffix === 'number') {
      off = Math.max(0, obj.size - r.suffix);
      len = obj.size - off;
    }
    h.set('Content-Range', `bytes ${off}-${off + len - 1}/${obj.size}`);
    h.set('Content-Length', String(len));
    return new Response(obj.body, { status: 206, headers: h });
  }
  h.set('Content-Length', String(obj.size));
  return new Response(obj.body, { headers: h });
}

// ---------- Thumbnails ----------
// ---------- 缩略图 ----------

// The uploading client renders the thumbnail (image crop, video frame pick, PDF/text screenshot)
// and posts it here as WebP. The server only checks the magic bytes and the size cap -- and always
// serves the result as image/webp + nosniff, so a bogus "thumbnail" can never become same-origin
// script (the /cid lesson).
// 缩略图由上传端渲染(图片裁切、视频选帧、PDF/文本截图),以 WebP POST 到这里。服务端只验魔数
// 和大小上限 —— 且永远按 image/webp + nosniff 回出去,假"缩略图"成不了同源脚本(/cid 的教训)。
driveApp.post('/files/:id/thumb', async (c) => {
  const a = await accessNode(c, c.req.param('id'), 'edit');
  if (a.node.kind !== 'file' || !a.node.r2_key) throw new HttpError(400, 'e_drive_not_file');
  const len = parseInt(c.req.header('Content-Length') || '', 10);
  if (!Number.isFinite(len) || len <= 0) throw new HttpError(400, 'e_drive_body_required');
  if (len > THUMB_MAX_BYTES) throw new HttpError(413, 'e_drive_part_too_big');
  const buf = await c.req.arrayBuffer();
  if (buf.byteLength > THUMB_MAX_BYTES) throw new HttpError(413, 'e_drive_part_too_big');
  const b = new Uint8Array(buf);
  const tag = (o: number) => String.fromCharCode(b[o], b[o + 1], b[o + 2], b[o + 3]);
  if (b.length < 12 || tag(0) !== 'RIFF' || tag(8) !== 'WEBP') throw new HttpError(400, 'e_bad_request');
  await c.env.RAW.put(a.node.r2_key + THUMB_SUFFIX, buf, { httpMetadata: { contentType: 'image/webp' } });
  await c.env.DB.prepare('UPDATE drive_nodes SET has_thumb=1 WHERE id=?1').bind(a.node.id).run();
  // The uploader's own stream cache may still say has_thumb=0 / 上传者自己的流缓存可能还记着没有缩略图
  accessCache.delete(c.get('user').id + ':' + a.node.id);
  return c.json({ ok: true });
});

driveApp.get('/files/:id/thumb', async (c) => {
  const node = await accessFileCached(c, c.req.param('id'));
  if (node.kind !== 'file' || !node.r2_key || !node.has_thumb) {
    throw new HttpError(404, 'e_drive_not_found');
  }
  const obj: any = await c.env.RAW.get(node.r2_key + THUMB_SUFFIX);
  if (!obj) throw new HttpError(404, 'e_drive_not_found');
  return new Response(obj.body, {
    headers: {
      'Content-Type': 'image/webp',
      'Content-Length': String(obj.size),
      'X-Content-Type-Options': 'nosniff',
      'Cache-Control': 'private, max-age=86400',
    },
  });
});

// ---------- Sharing ----------
// ---------- 共享 ----------

/** Do the two users have at least one domain in common (each holding some mailbox there)?
 *  两个用户是否至少同属一个域名(各自在该域名下有邮箱)? */
async function sharesDomainWith(env: Env, ownerId: string, userId: string): Promise<boolean> {
  const row = await env.DB.prepare(
    `SELECT 1 AS ok FROM grants g1 JOIN mailboxes m1 ON m1.id=g1.mailbox_id
     WHERE g1.user_id=?1 AND m1.domain_id IN (
       SELECT m2.domain_id FROM grants g2 JOIN mailboxes m2 ON m2.id=g2.mailbox_id WHERE g2.user_id=?2)
     LIMIT 1`
  ).bind(ownerId, userId).first();
  return !!row;
}

const SHARE_ROLES = ['viewer', 'editor'];
// agent: the reader is a program holding the link (see the /ai section). It may write, because
// that is what it is for, and it never expires, because nothing is watching it to renew.
// agent:读者是持有链接的程序(见 /ai 一节)。它可以写,因为这正是它的用途;
// 它永不过期,因为没有人守在旁边给它续期。
const SHARE_AUDIENCES = ['internal', 'public', 'agent'];
const SHARE_MAX_ITEMS = 100;
/** The nine the interface actually ships. An allowlist rather than a length cap: this value is
 *  handed straight back to every visitor, and only a code we have a dictionary for is useful.
 *  界面实际提供的九种。用白名单而非长度截断:这个值会原样发给每一位访问者,
 *  只有我们有词典的语言代码才有意义。 */
const SHARE_LANGS = new Set(['zh-CN', 'zh-TW', 'en', 'ja', 'ko', 'de', 'fr', 'es', 'ru']);

/** A share row plus the reason it is (or is not) usable right now.
 *  一条共享,外加它此刻可用/不可用的原因。 */
const SHARE_MAX_DAYS = 3650;

/** Expiry is expressed as a DURATION by the caller and turned into an instant here, on the
 *  server clock. Taking an absolute timestamp from the browser would hand the deadline to a
 *  clock nobody controls: a client running slow sends an instant that has "already passed",
 *  which used to be stored as null -- a link the user believed would expire in a week, living
 *  forever. A fast clock is the mirror image, keeping the link alive past its intended death.
 *  过期时间由调用方以"时长"表达,在此按服务器时钟换算成时刻。接受浏览器给的绝对时间戳,
 *  等于把有效期交给一个谁也管不着的时钟:走慢的客户端送来一个"已经过去"的时刻,
 *  过去会被存成 null —— 用户以为一周后失效的链接,成了永久链接。走快的时钟则相反,
 *  让链接活过它本该死去的时间。 */
function expiryFromDays(v: unknown, from: number = now()): number | null {
  const days = Number(v);
  if (!Number.isFinite(days) || days <= 0) return null;
  return from + Math.min(Math.floor(days), SHARE_MAX_DAYS) * 86400000;
}

function shareLiveness(s: any): string | null {
  if (!s) return 'e_drive_share_not_found';
  if (s.revoked_at) return 'e_drive_share_revoked';
  if (s.expires_at && s.expires_at <= now()) return 'e_drive_share_expired';
  return null;
}

/** Items of a share, minus anything trashed or deleted since. Sharing a node does not pin it:
 *  the owner can still bin it, and it then quietly leaves every share it was in.
 *  共享的条目,剔除此后被回收或删除的。共享不会钉住节点:所有者照样可以把它扔进回收站,
 *  它便悄然退出所有包含它的共享。 */
async function shareItems(env: Env, shareId: string): Promise<NodeRow[]> {
  const rows = await env.DB.prepare(
    `SELECT n.* FROM drive_share_items si JOIN drive_nodes n ON n.id = si.node_id
      WHERE si.share_id = ?1 ORDER BY n.kind DESC, n.name`
  ).bind(shareId).all();
  const out: NodeRow[] = [];
  for (const n of (rows.results || []) as unknown as NodeRow[]) {
    const chain = await chainOf(env, n.id);
    if (chain.length && !chain.some((x) => x.trashed)) out.push(n);
  }
  return out;
}

async function ownShare(c: any): Promise<any> {
  const s = await c.env.DB.prepare('SELECT * FROM drive_shares WHERE id=?1').bind(c.req.param('id')).first();
  if (!s || s.owner_id !== (c.get('user') as User).id) throw new HttpError(404, 'e_drive_share_not_found');
  return s;
}

/** Domains the caller may aim a share at: those where they actually hold a mailbox. Offering
 *  any other domain would let someone address a department they are not in.
 *  调用者可用来限定共享的域名:他确实持有信箱的那些。给出别的域名,
 *  等于让人对着自己并不属于的部门发共享。 */
async function myDomains(env: Env, userId: string): Promise<{ id: string; name: string }[]> {
  const rows = await env.DB.prepare(
    `SELECT DISTINCT d.id, d.name FROM grants g
       JOIN mailboxes m ON m.id = g.mailbox_id JOIN domains d ON d.id = m.domain_id
      WHERE g.user_id = ?1 ORDER BY d.name`
  ).bind(userId).all();
  return (rows.results || []) as any[];
}

driveApp.get('/share-domains', async (c) => c.json({ domains: await myDomains(c.env, c.get('user').id) }));

/** Create a share over any mix of files and folders. Public shares are forced to viewer here
 *  as well as in the UI: the public endpoints below never authenticate anyone, so an editable
 *  public share would be an unauthenticated write endpoint.
 *  在任意文件与目录的组合上创建共享。public 在此与界面两处都被钉死为 viewer:
 *  下面的公开端点从不认证任何人,可编辑的公开共享等于一个免认证的写入端点。 */
driveApp.post('/shares', async (c) => {
  const user: User = c.get('user');
  const body = await c.req.json<any>();
  const ids: string[] = Array.isArray(body.nodes) ? body.nodes.map((x: any) => String(x)) : [];
  if (!ids.length || ids.length > SHARE_MAX_ITEMS) throw new HttpError(400, 'e_bad_request');
  const audience = SHARE_AUDIENCES.includes(body.audience) ? body.audience : 'internal';
  const role = audience === 'public' ? 'viewer' : (SHARE_ROLES.includes(body.role) ? body.role : 'viewer');
  let domainId: string | null = null;
  if (audience === 'internal' && body.domain_id) {
    const mine = await myDomains(c.env, user.id);
    if (!mine.some((d) => d.id === body.domain_id)) throw new HttpError(400, 'e_drive_share_domain');
    domainId = String(body.domain_id);
  }
  // Every item must be owned by the caller and out of the trash
  // 每个条目都必须属于调用者且不在回收站
  const nodes: NodeRow[] = [];
  for (const id of ids) {
    const a = await accessNode(c, id, 'owner');
    if (a.chain.some((n) => n.trashed)) throw new HttpError(400, 'e_drive_trashed');
    nodes.push(a.node);
  }
  const shareId = uid();
  const token = randomToken(24);
  // One instant for both stamps: "expires in 7 days" should be exactly seven days after the
  // creation time recorded on the same row, not seven days after a moment a few queries earlier.
  // 两个时间戳取同一时刻:"7 天后过期"应当正好是同一行所记创建时间之后的七天,
  // 而不是几次查询之前那一刻之后的七天。
  const t = now();
  // An agent link has no deadline to offer: whatever holds it is not going to come back and ask
  // for a fresh one, so the only way it ends is the owner ending it.
  // 面向 AI 的链接没有期限可给:持有它的东西不会回来讨一条新的,
  // 于是它唯一的终点就是所有者亲手结束它。
  const expires = audience === 'agent' ? null : expiryFromDays(body.expires_days, t);
  // Remember how the sharer's app looked and read, so the public page can open the same way
  // 记下分享者当时的界面观感与语言,公开页据此以同样的样子打开
  const theme = String(body.theme || '').slice(0, 32) || null;
  const mode = body.mode === 'dark' ? 'dark' : (body.mode === 'light' ? 'light' : null);
  const lang = SHARE_LANGS.has(String(body.lang || '')) ? String(body.lang) : null;
  // Settle the disclosure question HERE, not when someone opens the link. A link states what it
  // will show at the moment it is handed out; re-reading the administrator's switch at view time
  // would let a later flip start printing an address on links whose sender never agreed to it.
  // 在"此处"了结披露问题,而不是在有人打开链接时。链接在交出去的那一刻就声明了它会显示什么;
  // 浏览时再去读管理员的开关,会让后来的一次拨动,开始在发出者从未同意过的链接上印出地址。
  const showOwner = await c.env.DB.prepare(
    `SELECT 1 AS ok FROM grants g JOIN mailboxes m ON m.id=g.mailbox_id
       JOIN domains d ON d.id=m.domain_id
      WHERE g.user_id=?1 AND d.drive_share_show_owner=1 LIMIT 1`
  ).bind(user.id).first();
  const stmts = [c.env.DB.prepare(
    `INSERT INTO drive_shares (id, token, owner_id, role, audience, domain_id, expires_at, note, theme, mode, lang, show_owner, created_at)
     VALUES (?1,?2,?3,?4,?5,?6,?7,?8,?9,?10,?11,?12,?13)`
  ).bind(shareId, token, user.id, role, audience, domainId, expires, cleanNote(body.note), theme, mode, lang, showOwner ? 1 : 0, t)];
  for (const n of nodes) {
    stmts.push(c.env.DB.prepare('INSERT INTO drive_share_items (share_id, node_id) VALUES (?1,?2)')
      .bind(shareId, n.id));
  }
  await c.env.DB.batch(stmts);
  return c.json({ id: shareId, token, role, audience, domain_id: domainId, expires_at: expires, created_at: t });
});

function cleanNote(v: unknown): string {
  return String(v ?? '').replace(/[\u0000-\u001f\u007f]/g, '').trim().slice(0, 200);
}

/** Everything the caller has shared out, with what is in it. This is the management list.
 *  调用者分享出去的一切,连同其内容。这就是管理列表。 */
driveApp.get('/shares', async (c) => {
  const rows = await c.env.DB.prepare(
    `SELECT s.*, d.name AS domain_name FROM drive_shares s
       LEFT JOIN domains d ON d.id = s.domain_id
      WHERE s.owner_id = ?1 ORDER BY s.created_at DESC LIMIT 300`
  ).bind(c.get('user').id).all();
  const out: any[] = [];
  for (const s of (rows.results || []) as any[]) {
    const items = await shareItems(c.env, s.id);
    const members = await c.env.DB.prepare(
      `SELECT m.user_id, m.joined_at, u.name, u.email FROM drive_share_members m
         JOIN users u ON u.id = m.user_id WHERE m.share_id = ?1 ORDER BY m.joined_at`
    ).bind(s.id).all();
    out.push({
      id: s.id, token: s.token, role: s.role, audience: s.audience,
      domain_id: s.domain_id, domain_name: s.domain_name || null,
      expires_at: s.expires_at, revoked_at: s.revoked_at, note: s.note, created_at: s.created_at,
      state: shareLiveness(s) || 'ok',
      items: items.map((n) => ({ id: n.id, name: n.name, kind: n.kind, size: n.size })),
      members: members.results || [],
    });
  }
  return c.json({ shares: out });
});

driveApp.put('/shares/:id', async (c) => {
  const s = await ownShare(c);
  const body = await c.req.json<any>();
  const sets: string[] = [];
  const args: any[] = [];
  if (body.role !== undefined) {
    if (!SHARE_ROLES.includes(body.role)) throw new HttpError(400, 'e_bad_request');
    // A public link can never be granted write access / 公开链接永远拿不到写权限
    if (s.audience === 'public' && body.role !== 'viewer') throw new HttpError(400, 'e_drive_share_public_readonly');
    sets.push(`role=?${sets.length + 1}`);
    args.push(body.role);
  }
  // Same rule on update: a duration from the caller, an instant from this clock.
  // 更新时同理:调用方给时长,时刻由本机时钟决定。
  if (body.expires_days !== undefined) {
    sets.push(`expires_at=?${sets.length + 1}`);
    args.push(expiryFromDays(body.expires_days));
  }
  if (body.note !== undefined) {
    sets.push(`note=?${sets.length + 1}`);
    args.push(cleanNote(body.note));
  }
  if (!sets.length) throw new HttpError(400, 'e_bad_request');
  await c.env.DB.prepare(`UPDATE drive_shares SET ${sets.join(',')} WHERE id=?${sets.length + 1}`)
    .bind(...args, s.id).run();
  return c.json({ ok: true });
});

/** Revoke. The row is kept (tombstoned) rather than deleted so the link dies immediately and
 *  visibly, and so a revoked entry can still be listed and explained rather than just vanishing.
 *  撤销。保留该行(打上墓碑)而非删除,链接因此立刻且显式地失效,
 *  且被撤销的条目仍能列出并给出说明,而不是凭空消失。 */
driveApp.delete('/shares/:id', async (c) => {
  const s = await ownShare(c);
  await c.env.DB.batch([
    c.env.DB.prepare('UPDATE drive_shares SET revoked_at=?1 WHERE id=?2').bind(now(), s.id),
    c.env.DB.prepare('DELETE FROM drive_share_members WHERE share_id=?1').bind(s.id),
  ]);
  return c.json({ ok: true });
});

/** Delete a revoked share for good, clearing it out of the management list.
 *  彻底删除一条已撤销的共享,把它从管理列表里清掉。 */
driveApp.post('/shares/:id/forget', async (c) => {
  const s = await ownShare(c);
  await c.env.DB.batch([
    c.env.DB.prepare('DELETE FROM drive_share_items WHERE share_id=?1').bind(s.id),
    c.env.DB.prepare('DELETE FROM drive_share_members WHERE share_id=?1').bind(s.id),
    c.env.DB.prepare('DELETE FROM drive_shares WHERE id=?1').bind(s.id),
  ]);
  return c.json({ ok: true });
});

driveApp.delete('/shares/:id/members/:userId', async (c) => {
  const userId = c.req.param('userId');
  // The owner can remove anyone; a member may remove themselves (leave the share)
  // 所有者可移除任何人;成员可以移除自己(退出共享)
  if (userId === c.get('user').id) {
    await c.env.DB.prepare('DELETE FROM drive_share_members WHERE share_id=?1 AND user_id=?2')
      .bind(c.req.param('id'), userId).run();
    return c.json({ ok: true });
  }
  const s = await ownShare(c);
  await c.env.DB.prepare('DELETE FROM drive_share_members WHERE share_id=?1 AND user_id=?2')
    .bind(s.id, userId).run();
  return c.json({ ok: true });
});

/** Opening an internal share link. Requires a signed-in account on this instance, and -- when
 *  the share names a domain -- a mailbox under it. Joining files it under "Shared with me".
 *  打开内部共享链接。需要本实例的登录账号;若共享指定了域名,还需在该域名下有信箱。
 *  加入后出现在其「共享给我」列表。 */
driveApp.post('/shares/join', async (c) => {
  const user = c.get('user');
  const token = String((await c.req.json<any>()).token || '');
  if (!token) throw new HttpError(400, 'e_bad_request');
  const s = await c.env.DB.prepare('SELECT * FROM drive_shares WHERE token=?1').bind(token).first<any>();
  const bad = shareLiveness(s);
  if (bad) throw new HttpError(bad === 'e_drive_share_not_found' ? 404 : 403, bad);
  if (!SHARE_AUDIENCES.includes(s.audience)) throw new HttpError(404, 'e_drive_share_not_found');
  const items = await shareItems(c.env, s.id);
  if (!items.length) throw new HttpError(404, 'e_drive_share_not_found');
  if (s.owner_id !== user.id) {
    // Who may keep a link decides nothing new about who may open it. An internal link still
    // has to clear the company (and the department, when one is named); a public link is by
    // definition open to whoever holds it, so there is nothing further to check -- keeping it
    // is exactly as read-only as opening it was.
    // "谁可以留下这条链接",不会对"谁可以打开它"作出任何新的裁定。内部链接仍须过企业这一关
    // (指定了部门的还要过部门);公开链接按定义对任何拿到它的人开放,因此无可再验 ——
    // 留下它,与打开它一样只读。
    if (s.audience === 'internal') {
      if (s.domain_id) {
        const mine = await myDomains(c.env, user.id);
        if (!mine.some((d) => d.id === s.domain_id)) throw new HttpError(403, 'e_drive_share_domain');
      } else if (!(await sharesDomainWith(c.env, s.owner_id, user.id))) {
        throw new HttpError(403, 'e_drive_share_domain');
      }
    }
    await c.env.DB.prepare('INSERT OR IGNORE INTO drive_share_members (share_id, user_id, joined_at) VALUES (?1,?2,?3)')
      .bind(s.id, user.id, now()).run();
  }
  return c.json({
    share_id: s.id, role: s.role,
    // The sharer opening their own link joins nothing -- there is no membership row for them,
    // so "shared items" would be empty and landing there would read as a broken link.
    // 分享者打开自己的链接不会加入任何东西 —— 他没有成员记录,"共享给我"因此是空的,
    // 落到那里会让人以为链接坏了。
    owner: s.owner_id === user.id,
    items: items.map((n) => ({ id: n.id, name: n.name, kind: n.kind })),
  });
});

driveApp.get('/shared', async (c) => {
  const rows = await c.env.DB.prepare(
    `SELECT s.id AS share_id, s.role, s.expires_at, s.revoked_at, m.joined_at,
            u.name AS owner_name, u.email AS owner_email
     FROM drive_share_members m JOIN drive_shares s ON s.id=m.share_id JOIN users u ON u.id=s.owner_id
     WHERE m.user_id=?1 ORDER BY m.joined_at DESC LIMIT 200`
  ).bind(c.get('user').id).all();
  const out: any[] = [];
  for (const r of (rows.results || []) as any[]) {
    if (shareLiveness(r)) continue; // revoked or expired shares drop off the list / 已撤销或过期的不再列出
    for (const n of await shareItems(c.env, r.share_id)) {
      out.push({ share_id: r.share_id, node_id: n.id, name: n.name, kind: n.kind, size: n.size,
        role: r.role, joined_at: r.joined_at, owner_name: r.owner_name, owner_email: r.owner_email });
    }
  }
  return c.json({ shares: out });
});

// ---------- Public share access (no account) ----------
// ---------- 公开共享访问(无需账号) ----------
// Mounted outside the authenticated router. Everything here is read-only by construction:
// there is no caller identity to authorise a write against, so none of these endpoints can
// mutate anything, and `audience='public'` is refused write access at creation time too.
// 挂在需要认证的路由之外。此处一切按构造即只读:没有调用者身份可供授权写操作,
// 因此这些端点无一能修改任何东西,并且 audience='public' 在创建时也被拒绝写权限。

export const drivePubApp = new Hono<Ctx>();

// Never let a public response be reused from cache. Revocation and expiry must bite the moment
// they happen, and a cached 200 from five seconds ago would quietly outlive the link -- the one
// failure mode where the user believes access is cut off and it is not.
// 公开响应一律不得从缓存复用。撤销与过期必须在发生的那一刻生效,
// 而五秒前缓存下来的 200 会让链接悄悄活过它的死期 —— 这恰是最糟的失效模式:
// 用户以为访问已经切断,实际并没有。
drivePubApp.use('*', async (c, next) => {
  await next();
  c.header('Cache-Control', 'no-store');
});

async function pubShare(c: any): Promise<any> {
  const token = String(c.req.param('token') || '');
  if (!token) throw new HttpError(404, 'e_drive_share_not_found');
  const s = await c.env.DB.prepare("SELECT * FROM drive_shares WHERE token=?1 AND audience='public'")
    .bind(token).first();
  const bad = shareLiveness(s);
  if (bad) throw new HttpError(bad === 'e_drive_share_not_found' ? 404 : 403, bad);
  return s;
}

/** Resolve a node the public link is allowed to reach: it must sit at, or beneath, one of the
 *  share's items, and nothing on the way may be trashed. Without this check the token would be
 *  a key to the whole drive, since node ids are guessable in the sense that they are just ids.
 *  解析公开链接有权访问的节点:它必须是共享条目之一,或位于其下,且沿途不得有回收站中的节点。
 *  没有这道校验,token 就成了整个网盘的钥匙 —— 节点 id 只是 id,不该被当作凭证。 */
async function pubNode(c: any, share: any, nodeId: string): Promise<{ node: NodeRow; chain: NodeRow[]; roots: Set<string> }> {
  const chain = await chainOf(c.env, nodeId);
  if (!chain.length || chain.some((n) => n.trashed)) throw new HttpError(404, 'e_drive_not_found');
  const items = await shareItems(c.env, share.id);
  const roots = new Set(items.map((n) => n.id));
  if (!chain.some((n) => roots.has(n.id))) throw new HttpError(404, 'e_drive_not_found');
  return { node: chain[0], chain, roots };
}

/** Landing payload: what this link contains, and whether it is still alive.
 *  落地数据:这条链接包含什么,以及它是否仍然有效。 */
drivePubApp.get('/:token', async (c) => {
  const s = await pubShare(c);
  const items = await shareItems(c.env, s.id);
  const owner: any = await c.env.DB.prepare('SELECT name, email FROM users WHERE id=?1').bind(s.owner_id).first();
  // The answer was settled when the link was created and is read back from the link itself.
  // Nothing an administrator or the sharer changes afterwards moves it -- to stop a link that
  // is already out there from showing the address, revoke the link.
  // 这个答案在链接创建时就已了结,此处只从链接自身读回。
  // 管理员或分享者事后改什么都不会动它 —— 想让一条已经发出去的链接不再显示地址,请撤销它。
  return c.json({
    role: 'viewer',
    note: s.note,
    expires_at: s.expires_at,
    owner_name: owner?.name || '',
    owner_email: s.show_owner ? (owner?.email || '') : '',
    theme: s.theme || null,
    mode: s.mode || null,
    lang: s.lang || null,
    items: items.map((n) => nodeJson(n)),
  });
});

/** List inside the share. `parent` empty means the virtual root -- the selected items. */
/** 在共享内部列目录。parent 为空表示虚拟根 —— 即被选中的那些条目。 */
drivePubApp.get('/:token/list', async (c) => {
  const s = await pubShare(c);
  const parent = c.req.query('parent') || '';
  if (!parent) {
    const items = await shareItems(c.env, s.id);
    return c.json({ access: 'viewer', path: [], nodes: items.map((n) => nodeJson(n)) });
  }
  const { node, chain, roots } = await pubNode(c, s, parent);
  if (node.kind !== 'folder') throw new HttpError(400, 'e_drive_not_folder');
  const rows = await c.env.DB.prepare(
    'SELECT * FROM drive_nodes WHERE parent_id=?1 AND trashed=0 ORDER BY kind DESC, name'
  ).bind(node.id).all();
  // Breadcrumb stops at the shared item: the recipient must not learn the folders above it
  // 面包屑到共享条目为止:接收方不该看到它上面的目录结构
  const cut = chain.findIndex((n) => roots.has(n.id));
  const path = chain.slice(0, cut + 1).reverse().map((n) => ({ id: n.id, name: n.name }));
  return c.json({ access: 'viewer', path, nodes: (rows.results || []).map((n: any) => nodeJson(n)) });
});

/** Seed for the archive browser: name, size, and the breadcrumb down from the shared item.
 *  Cut at the share root exactly like the listing is -- a deep link into an archive must not
 *  reveal the folders the sharer kept above it.
 *  压缩包浏览器的种子:名称、大小,以及自共享条目往下的面包屑。
 *  与列目录一样在共享根处截断 —— 深链进一个压缩包,不该暴露分享者留在其上层的目录。 */
drivePubApp.get('/:token/nodes/:id/meta', async (c) => {
  const s = await pubShare(c);
  const { node, chain, roots } = await pubNode(c, s, c.req.param('id'));
  const cut = chain.findIndex((n) => roots.has(n.id));
  const path = chain.slice(1, cut + 1).reverse();
  return c.json({
    node: nodeJson(node, false),
    access: 'viewer',
    path: path.map((n) => ({ id: n.id, name: n.name })),
  });
});

drivePubApp.get('/:token/files/:id/dl', async (c) => {
  const s = await pubShare(c);
  const { node } = await pubNode(c, s, c.req.param('id'));
  return serveFile(c, node);
});

drivePubApp.get('/:token/files/:id/thumb', async (c) => {
  const s = await pubShare(c);
  const { node } = await pubNode(c, s, c.req.param('id'));
  if (node.kind !== 'file' || !node.r2_key || !node.has_thumb) throw new HttpError(404, 'e_drive_not_found');
  const obj: any = await c.env.RAW.get(node.r2_key + THUMB_SUFFIX);
  if (!obj) throw new HttpError(404, 'e_drive_not_found');
  return new Response(obj.body, {
    headers: {
      'Content-Type': 'image/webp',
      'Content-Length': String(obj.size),
      'X-Content-Type-Options': 'nosniff',
      'Cache-Control': 'private, max-age=86400',
    },
  });
});
// ---------- Agent access links (/agt/<token>) ----------
// ---------- 面向 AI 的访问链接(/agt/<token>) ----------
//
// A share for a reader that is a program. Everything an agent needs arrives in the first
// response: a handful of lines telling it which verbs exist, then the contents of the link.
// There is no manifest to install, no server to configure, no second document to fetch --
// the URL is the instructions, and every deeper URL is reached by appending a name to the one
// it just read.
//
// The token sits in the path, so a single string carries both "who may" and "what". There is
// no session, no header to set, nothing to remember between requests. That is the whole point
// and also the whole risk, and it is a deliberate trade the owner makes when creating the link:
// whoever holds it can do what the link says, until the owner revokes it.
//
// Written to be read by a language model, so it is written to be short. Read-only links do not
// mention writing at all -- describing a verb the link will refuse is worse than useless, it is
// tokens spent to produce a wrong attempt.
//
// 一份写给"读者是程序"的共享。代理所需的一切都在第一次响应里到齐:寥寥数行说明有哪些动词,
// 接着就是这条链接的内容。没有清单要安装,没有服务要配置,没有第二份文档要取 ——
// URL 本身就是说明书,而更深处的每个 URL,都由刚读到的那个 URL 追加一个名字得到。
//
// token 在路径里,于是一个字符串同时携带"谁可以"和"什么"。没有会话,没有要设的头,
// 请求之间不必记住任何东西。这既是它的全部意义,也是它的全部风险 ——
// 这是所有者在创建链接时有意做出的交换:持有者能做链接所说的事,直到所有者撤销它。
//
// 它是写给语言模型读的,所以写得短。只读链接压根不提写 ——
// 描述一个链接会拒绝的动词,比无用更糟:那是花掉 token 去换一次错误的尝试。

export const driveAgentApp = new Hono<Ctx>();

driveAgentApp.use('*', async (c, next) => {
  await next();
  // Revocation has to bite at once; a cached 200 would outlive the link.
  // 撤销必须立刻生效;缓存下来的 200 会让链接活过它的死期。
  c.header('Cache-Control', 'no-store');
  c.header('X-Robots-Tag', 'noindex, nofollow');
});

/** Plain text in, plain text out. These answers are read by a model, not rendered, so an error
 *  is a short sentence rather than a code the caller would have to look up.
 *  纯文本进,纯文本出。这些回答是给模型读的、不做渲染,所以错误是一句短话,
 *  而不是一个还要去查表的错误码。 */
const txt = (body: string, status = 200) =>
  new Response(body, {
    status,
    headers: { 'Content-Type': 'text/plain; charset=utf-8', 'X-Content-Type-Options': 'nosniff' },
  });

/** Sizes an agent reads to decide whether to fetch something, not to do arithmetic on.
 *  给代理判断"要不要取"用的大小,不是拿来做算术的。 */
function shortSize(n: number): string {
  if (n < 1024) return `${n}`;
  const units = ['K', 'M', 'G', 'T'];
  let v = n / 1024;
  let i = 0;
  while (v >= 1024 && i < units.length - 1) { v /= 1024; i++; }
  return `${v >= 10 ? Math.round(v) : v.toFixed(1)}${units[i]}`;
}

/** Enough of a type map that text an agent writes comes back as text. Anything unrecognised is
 *  octet-stream, which is the honest answer and still downloads and previews as a file.
 *  够用的类型表,好让代理写进去的文本能按文本回来。认不出的一律 octet-stream ——
 *  这是诚实的答案,而且照样能下载、能当文件预览。 */
const EXT_MIME: Record<string, string> = {
  txt: 'text/plain', md: 'text/markdown', csv: 'text/csv', tsv: 'text/tab-separated-values',
  json: 'application/json', jsonl: 'application/json', ndjson: 'application/json',
  yaml: 'text/yaml', yml: 'text/yaml', toml: 'text/plain', ini: 'text/plain', log: 'text/plain',
  html: 'text/html', css: 'text/css', js: 'text/javascript', mjs: 'text/javascript',
  ts: 'text/plain', tsx: 'text/plain', jsx: 'text/plain', py: 'text/x-python', sh: 'text/x-sh',
  sql: 'text/plain', xml: 'application/xml', svg: 'image/svg+xml', pdf: 'application/pdf',
  png: 'image/png', jpg: 'image/jpeg', jpeg: 'image/jpeg', gif: 'image/gif', webp: 'image/webp',
  zip: 'application/zip', mp4: 'video/mp4', mp3: 'audio/mpeg',
};

function mimeOf(name: string, declared?: string | null): string {
  const d = String(declared || '').toLowerCase().split(';')[0].trim();
  if (d && d !== 'application/octet-stream' && /^[a-z0-9.+-]+\/[a-z0-9.+-]+$/.test(d)) return d.slice(0, 120);
  const ext = (/\.([A-Za-z0-9]{1,12})$/.exec(name) || ['', ''])[1].toLowerCase();
  return EXT_MIME[ext] || 'application/octet-stream';
}

async function agentShare(env: Env, token: string): Promise<any | null> {
  if (!token) return null;
  const s = await env.DB.prepare("SELECT * FROM drive_shares WHERE token=?1 AND audience='agent'")
    .bind(token).first();
  return shareLiveness(s) ? null : s;
}

/** The names the selected items answer to at the top level. Two items may well arrive carrying
 *  the same name from different folders, and a path has to mean one thing, so a repeat gets a
 *  `~2` suffix. The order is shareItems' order, so the same share always yields the same names.
 *  被选中的条目在顶层各自应答的名字。两个条目完全可能从不同目录带来同一个名字,
 *  而一条路径只能有一个含义,所以重复者补一个 `~2` 后缀。
 *  顺序即 shareItems 的顺序,于是同一条共享永远得到同一组名字。 */
async function agentRoots(env: Env, shareId: string): Promise<Map<string, NodeRow>> {
  const out = new Map<string, NodeRow>();
  for (const n of await shareItems(env, shareId)) {
    let seg = n.name;
    for (let k = 2; out.has(seg); k++) seg = `${n.name}~${k}`;
    out.set(seg, n);
  }
  return out;
}

/** Walk a path of names down from the selection. Intermediate segments must be folders; the last
 *  one is a file if a file by that name exists, otherwise a folder -- so an agent that forgets
 *  the trailing slash on a folder still gets its listing instead of an error.
 *  从选中项出发,按名字逐级往下走。中间的段必须是目录;最后一段若有同名文件就是文件,
 *  否则是目录 —— 于是代理忘了给目录加尾斜杠,拿到的仍是列表而不是报错。 */
async function agentWalk(env: Env, roots: Map<string, NodeRow>, segs: string[]): Promise<NodeRow | null> {
  if (!segs.length) return null;
  let node = roots.get(segs[0]) || null;
  if (!node) return null;
  for (let i = 1; i < segs.length; i++) {
    if (node.kind !== 'folder') return null;
    const row: any = await env.DB.prepare(
      `SELECT * FROM drive_nodes WHERE parent_id=?1 AND name=?2 AND trashed=0
        ORDER BY kind='file' DESC LIMIT 1`
    ).bind(node.id, segs[i]).first();
    if (!row) return null;
    node = row as NodeRow;
  }
  return node;
}

async function agentList(env: Env, folderId: string): Promise<string> {
  const rows = await env.DB.prepare(
    `SELECT name, kind, size FROM drive_nodes WHERE parent_id=?1 AND trashed=0
      ORDER BY kind DESC, name LIMIT ${LIST_LIMIT}`
  ).bind(folderId).all();
  return (rows.results || []).map((n: any) =>
    n.kind === 'folder' ? `${n.name}/` : `${n.name}\t${shortSize(n.size || 0)}`).join('\n');
}

const rootList = (roots: Map<string, NodeRow>): string =>
  [...roots].map(([seg, n]) => (n.kind === 'folder' ? `${seg}/` : `${seg}\t${shortSize(n.size || 0)}`)).join('\n');

/** The whole instruction manual. Every line here is paid for on every visit, so a line earns its
 *  place by preventing a wrong request -- and the verbs a read-only link refuses are not
 *  mentioned, because naming them would only buy a 403.
 *  整本说明书。这里每一行在每次访问时都要付账,所以一行要靠"能防住一次错误请求"来挣得位置 ——
 *  只读链接会拒绝的动词一概不提,提了只能换来一个 403。 */
function agentSkill(base: string, share: any, roots: Map<string, NodeRow>): string {
  const rw = share.role === 'editor';
  const lines = [
    `# Drive over HTTP (${rw ? 'read/write' : 'read-only'})`,
    '',
    `B=${base}`,
    '',
    'GET B/P/ list folder: a line per entry, "name/" is a folder, "name<tab>size" is a file',
    'GET B/P read file (Range ok)',
    ...(rw ? [
      'PUT B/P write file, body is the whole new content (creates or replaces)',
      'PUT B/P/ create folder',
      'DELETE B/P delete',
      'POST B/P?to=NAME rename',
    ] : []),
    '',
    'P is a path of names. Names in a listing are relative to the URL you fetched: append one to',
    'go deeper. Below is B itself.',
    ...(rw ? ['New items go inside one of these; the top level is fixed.'] : []),
    '',
    rootList(roots),
  ];
  return lines.join('\n') + '\n';
}

/** One handler for every method: the path is parsed the same way each time, and a trailing
 *  slash is meaningful, so it is read off the raw URL rather than from a router that may
 *  normalise it away.
 *  一个 handler 应付所有方法:路径每次都用同一套解析,而尾斜杠是有含义的,
 *  所以直接从原始 URL 上读,而不是交给可能把它规整掉的路由。 */
driveAgentApp.all('/*', async (c) => {
  const parts = new URL(c.req.url).pathname.split('/').slice(2);
  const token = parts.shift() || '';
  const wantDir = parts.length > 0 && parts[parts.length - 1] === '';
  if (wantDir) parts.pop();
  if (parts.some((s) => s === '')) return txt('bad path', 400);
  let segs: string[];
  try {
    segs = parts.map((s) => decodeURIComponent(s));
  } catch {
    return txt('bad path', 400);
  }
  // The URL parser collapses these before we ever see them, and a collapsed path can only land
  // on another token, never outside /agt. This is the backstop for the day that stops being true.
  // URL 解析器在我们看到之前就把它们折叠掉了,而折叠后的路径只可能落到另一个 token 上,
  // 出不了 /agt。这行是留给"哪天这条不再成立"的后手。
  if (segs.some((s) => s === '.' || s === '..')) return txt('bad path', 400);

  const share = await agentShare(c.env, token);
  // Wrong, revoked and expired answer alike: a link that no longer works is not worth
  // explaining to a program, and the distinction would only describe someone else's link.
  // 错误的、已撤销的、已过期的一律同一个回答:失效的链接不值得向程序解释,
  // 而分辨它们只会泄露别人那条链接的状态。
  if (!share) return txt('no such link', 404);
  const method = c.req.method;
  const write = method === 'PUT' || method === 'DELETE' || method === 'POST';
  if (write && share.role !== 'editor') return txt('read-only link', 403);

  const roots = await agentRoots(c.env, share.id);
  const node = segs.length ? await agentWalk(c.env, roots, segs) : null;

  if (method === 'GET' || method === 'HEAD') {
    if (!segs.length) {
      // Taken from the request, not from a configured value: this instance answers on five
      // domains and the agent must be sent back to the one it actually reached. (wrangler dev
      // rewrites both the URL and the Host header to the first configured route, so the base
      // printed by a local server names a production host. Nothing to fix -- there is no
      // localhost answer to be had from a request that no longer says localhost.)
      // 取自请求本身,而不是某个配置值:本实例应答五个域名,必须把代理指回它真正到达的那个。
      // (wrangler dev 会把 URL 和 Host 头一起改写成配置里的第一条路由,
      // 因此本地服务器印出的 base 写的是生产域名。这没什么可修的 ——
      // 一个已经不再自称 localhost 的请求,给不出 localhost 这个答案。)
      const base = new URL(c.req.url).origin + '/agt/' + token;
      return txt(agentSkill(base, share, roots));
    }
    if (!node) return txt('no such path', 404);
    if (node.kind === 'folder') return txt(await agentList(c.env, node.id) + '\n');
    const r = await serveFile(c, node);
    // Say utf-8 out loud on text. A browser has a document to take the encoding from; a program
    // reading `text/plain` with no charset is entitled to fall back to latin-1, and then every
    // non-ASCII file in the drive comes back as mojibake.
    // 文本要把 utf-8 说出口。浏览器有文档可据以推断编码;而一个读到不带 charset 的 text/plain
    // 的程序,有权退回 latin-1 —— 于是网盘里每个非 ASCII 文件都变成乱码。
    const ct = r.headers.get('Content-Type') || '';
    if (!ct.includes('charset') && /^(text\/|application\/(json|xml))/.test(ct)) {
      r.headers.set('Content-Type', `${ct}; charset=utf-8`);
    }
    return r;
  }

  if (method === 'DELETE') {
    if (!node) return txt('no such path', 404);
    // Into the owner's trash, not out of existence: the link is a convenience, and a convenience
    // should not be the one door in this system that destroys something irreversibly.
    // 进所有者的回收站,而不是从世上消失:这条链接图的是方便,
    // 而方便不该成为本系统里唯一一扇能不可逆地毁掉东西的门。
    const stmts = [
      c.env.DB.prepare('UPDATE drive_nodes SET trashed=1, trashed_at=?1, updated_at=?1 WHERE id=?2')
        .bind(now(), node.id),
    ];
    const ad = ancDelta(c.env, node.parent_id, -nodeBytes(node));
    if (ad) stmts.push(ad);
    await c.env.DB.batch(stmts);
    return txt('ok');
  }

  if (method === 'POST') {
    if (!node) return txt('no such path', 404);
    let name: string;
    try {
      name = cleanName(c.req.query('to'));
    } catch {
      return txt('bad name', 400);
    }
    if (await findClash(c.env, node.owner_id, node.parent_id, name, node.kind)) return txt('name taken', 409);
    await c.env.DB.prepare('UPDATE drive_nodes SET name=?1, updated_at=?2 WHERE id=?3')
      .bind(name, now(), node.id).run();
    return txt('ok');
  }

  // PUT: the last segment is the name being written, everything before it says where.
  // PUT:最后一段是要写的名字,它前面的部分说明写在哪儿。
  if (method !== 'PUT') return txt('unsupported method', 405);
  const fixed = 'the top level is fixed; write inside a listed folder';
  if (!segs.length) return txt(fixed, 400);

  // A top-level name is not a place to create things -- the root is the selection, not a folder.
  // But writing to something already listed there replaces it, and that is the whole point of
  // sharing one file with an agent: it has no folder here to put a new file in, only that file.
  // 顶层的名字不是可供创建的地方 —— 根是"所选内容",不是目录。
  // 但写到已经列在那里的东西上,是替换它;而这正是"把一个文件分享给 AI"的全部意义:
  // 它在这里没有目录可放新文件,只有那一个文件。
  let parent: NodeRow | null = null;
  let name: string;
  let clash: NodeRow | null = null;
  if (segs.length === 1) {
    if (!node) return txt(fixed, 400);
    if (wantDir) return node.kind === 'folder' ? txt('ok') : txt('not a folder', 400);
    if (node.kind !== 'file') return txt('not a file', 400);
    clash = node;
    name = node.name;
  } else {
    parent = await agentWalk(c.env, roots, segs.slice(0, -1));
    if (!parent) return txt('no such folder', 404);
    if (parent.kind !== 'folder') return txt('not a folder', 400);
    try {
      name = cleanName(segs[segs.length - 1]);
    } catch {
      return txt('bad name', 400);
    }
  }
  const ownerId = clash ? clash.owner_id : parent!.owner_id;
  const parentId = clash ? clash.parent_id : parent!.id;
  const q0 = await driveQuota(c.env, ownerId);
  if (!q0.enabled) return txt('drive disabled', 403);

  if (wantDir) {
    const existing = await findClash(c.env, ownerId, parentId, name, 'folder');
    if (existing) return txt('ok');
    const chain = await chainOf(c.env, parent!.id);
    if (chain.length >= DEPTH_MAX - 1) return txt('too deep', 400);
    const t = now();
    await c.env.DB.prepare(
      `INSERT INTO drive_nodes (id, owner_id, parent_id, kind, name, created_at, updated_at)
       VALUES (?1,?2,?3,'folder',?4,?5,?5)`
    ).bind(uid(), ownerId, parentId, name, t).run();
    return txt('ok');
  }

  const len = parseInt(c.req.header('Content-Length') || '', 10);
  if (!c.req.raw.body || !Number.isFinite(len) || len < 0) return txt('body required', 400);
  if (len > SINGLE_MAX) return txt(`too big, max ${shortSize(SINGLE_MAX)}`, 413);
  if (!clash) clash = await findClash(c.env, ownerId, parentId, name, 'file');
  const oldSize = clash?.size || 0;
  if (q0.used - oldSize + len > q0.quota) return txt('out of space', 413);
  const mime = mimeOf(name, c.req.header('Content-Type'));
  const id = clash ? clash.id : uid();
  const key = clash?.r2_key || `drive/${ownerId}/${id}`;
  const obj: any = await c.env.RAW.put(key, c.req.raw.body, { httpMetadata: { contentType: mime } });
  const size = obj?.size ?? len;
  const t = now();
  const stmts = clash
    ? [
      c.env.DB.prepare('UPDATE drive_nodes SET mime=?1, size=?2, has_thumb=0, updated_at=?3 WHERE id=?4')
        .bind(mime, size, t, id),
      c.env.DB.prepare('UPDATE users SET drive_bytes=MAX(drive_bytes+?1,0) WHERE id=?2')
        .bind(size - oldSize, ownerId),
    ]
    : [
      c.env.DB.prepare(
        `INSERT INTO drive_nodes (id, owner_id, parent_id, kind, name, mime, size, r2_key, created_at, updated_at)
         VALUES (?1,?2,?3,'file',?4,?5,?6,?7,?8,?8)`
      ).bind(id, ownerId, parentId, name, mime, size, key, t),
      c.env.DB.prepare('UPDATE users SET drive_bytes=MAX(drive_bytes+?1,0) WHERE id=?2').bind(size, ownerId),
    ];
  // The stale thumbnail dies with the bytes it described / 旧缩略图随它所描述的字节一起作废
  if (clash) await c.env.RAW.delete(key + THUMB_SUFFIX).catch(() => {});
  const ad = ancDelta(c.env, parentId, size - oldSize);
  if (ad) stmts.push(ad);
  await c.env.DB.batch(stmts);
  return txt('ok');
});

// ---------- Admin API (/api/admin/drive) ----------
// ---------- 管理端 API(/api/admin/drive) ----------

export const driveAdminApp = new Hono<Ctx>();

driveAdminApp.get('/domains', async (c) => {
  const scope = await adminScope(c);
  const rows = await c.env.DB.prepare('SELECT id, name, drive_enabled, drive_quota_mb, drive_share_show_owner FROM domains ORDER BY name').all();
  let list = (rows.results || []) as any[];
  if (scope) list = list.filter((d) => scope.has(d.id));
  return c.json({ domains: list, hard_cap_mb: DRIVE_HARD_CAP_MB });
});

driveAdminApp.post('/domains/:id', async (c) => {
  const id = c.req.param('id');
  await checkDomainScope(c, id);
  const body = await c.req.json<any>();
  const sets: string[] = [];
  const vals: any[] = [];
  if (body.enabled !== undefined) {
    sets.push(`drive_enabled=?${vals.length + 1}`);
    vals.push(body.enabled ? 1 : 0);
  }
  if (body.quota_mb !== undefined) {
    const q = Math.floor(Number(body.quota_mb));
    if (!Number.isFinite(q) || q < 1 || q > DRIVE_HARD_CAP_MB) throw new HttpError(400, 'e_drive_bad_quota');
    sets.push(`drive_quota_mb=?${vals.length + 1}`);
    vals.push(q);
  }
  // Whether a public share link may print the sharer's address. An administrator decision, not
  // the sharer's: it governs what leaves the company, so it cannot sit in the share dialog.
  // 公开分享链接是否可以印出分享者的地址。这是管理员的决定,不是分享者的:
  // 它管的是什么东西流出企业,因此不能放在分享对话框里。
  if (body.share_show_owner !== undefined) {
    sets.push(`drive_share_show_owner=?${vals.length + 1}`);
    vals.push(body.share_show_owner ? 1 : 0);
  }
  if (sets.length) {
    vals.push(id);
    await c.env.DB.prepare(`UPDATE domains SET ${sets.join(',')} WHERE id=?${vals.length}`).bind(...vals).run();
    await audit(c.env, c.get('user'), 'drive.settings', undefined,
      { enabled: body.enabled, quota_mb: body.quota_mb, share_show_owner: body.share_show_owner }, id);
  }
  return c.json({ ok: true });
});

driveAdminApp.get('/users', async (c) => {
  const scope = await adminScope(c);
  const q = String(c.req.query('q') || '').trim().slice(0, 100);
  const binds: any[] = [];
  const where: string[] = [];
  if (scope) {
    const ids = [...scope];
    where.push(`EXISTS (SELECT 1 FROM grants g JOIN mailboxes mb ON mb.id=g.mailbox_id
      WHERE g.user_id=u.id AND mb.domain_id IN (${ids.map((_, i) => '?' + (binds.length + i + 1)).join(',')}))`);
    binds.push(...ids);
  }
  if (q) {
    const like = '%' + q.replace(/[\\%_]/g, (ch) => '\\' + ch) + '%';
    where.push(`(u.email LIKE ?${binds.length + 1} ESCAPE '\\' OR u.name LIKE ?${binds.length + 1} ESCAPE '\\')`);
    binds.push(like);
  }
  const rows = await c.env.DB.prepare(
    `SELECT u.id, u.email, u.name, u.drive_quota_mb AS user_mb, u.drive_bytes AS used,
       (SELECT COUNT(*) FROM drive_nodes n WHERE n.owner_id=u.id AND n.kind='file') AS files,
       (SELECT MAX(d.drive_quota_mb) FROM domains d WHERE d.drive_enabled=1 AND d.id IN
         (SELECT mb2.domain_id FROM grants g2 JOIN mailboxes mb2 ON mb2.id=g2.mailbox_id WHERE g2.user_id=u.id)) AS dom_mb
     FROM users u ${where.length ? 'WHERE ' + where.join(' AND ') : ''}
     ORDER BY used DESC, u.email LIMIT 200`
  ).bind(...binds).all();
  const users = ((rows.results || []) as any[]).map((r) => ({
    id: r.id, email: r.email, name: r.name,
    used: r.used || 0, files: r.files || 0,
    quota_mb: r.user_mb, default_mb: r.dom_mb,
    effective_mb: r.dom_mb == null ? 0 : Math.min(r.user_mb ?? r.dom_mb, DRIVE_HARD_CAP_MB),
    enabled: r.dom_mb != null,
  }));
  return c.json({ users, hard_cap_mb: DRIVE_HARD_CAP_MB });
});

driveAdminApp.post('/users/:id', async (c) => {
  const scope = await adminScope(c);
  const id = c.req.param('id');
  const target = await c.env.DB.prepare('SELECT id, email FROM users WHERE id=?1').bind(id).first<any>();
  if (!target) throw new HttpError(404, 'e_user_not_found');
  if (scope) {
    const ids = [...scope];
    const hit = await c.env.DB.prepare(
      `SELECT 1 AS ok FROM grants g JOIN mailboxes mb ON mb.id=g.mailbox_id
       WHERE g.user_id=?1 AND mb.domain_id IN (${ids.map((_, i) => '?' + (i + 2)).join(',')}) LIMIT 1`
    ).bind(id, ...ids).first();
    if (!hit) throw new HttpError(403, 'e_no_domain_perm');
  }
  const body = await c.req.json<any>();
  let quota: number | null = null;
  if (body.quota_mb !== null && body.quota_mb !== undefined && body.quota_mb !== '') {
    quota = Math.floor(Number(body.quota_mb));
    if (!Number.isFinite(quota) || quota < 1 || quota > DRIVE_HARD_CAP_MB) throw new HttpError(400, 'e_drive_bad_quota');
  }
  await c.env.DB.prepare('UPDATE users SET drive_quota_mb=?1 WHERE id=?2').bind(quota, id).run();
  await audit(c.env, c.get('user'), 'drive.quota', target.email, { quota_mb: quota });
  return c.json({ ok: true });
});

// ---------- Cron hooks ----------
// ---------- 定时任务 ----------

/** Hourly: abort multipart uploads that never completed
 *  每小时:中止一直没完成的分片上传 */
export async function driveCronHourly(env: Env): Promise<void> {
  const olds = await env.DB.prepare('SELECT * FROM drive_uploads WHERE created_at<?1 LIMIT 50')
    .bind(now() - UPLOAD_STALE_MS).all();
  for (const u of (olds.results || []) as any[]) {
    try {
      await env.RAW.resumeMultipartUpload(u.r2_key, u.upload_id).abort();
    } catch {}
    await env.DB.prepare('DELETE FROM drive_uploads WHERE id=?1').bind(u.id).run();
  }
}

/** Daily: purge trash older than 30 days, bounded per run (a huge subtree simply continues tomorrow)
 *  每天:清理回收站中超过 30 天的内容,每次运行有上限(特别大的子树明天接着删) */
export async function driveCronDaily(env: Env): Promise<void> {
  for (let i = 0; i < 3; i++) {
    const row = await env.DB.prepare('SELECT id FROM drive_nodes WHERE trashed=1 AND trashed_at<?1 LIMIT 1')
      .bind(now() - TRASH_KEEP_MS).first<any>();
    if (!row) break;
    await purgeSubtree(env, row.id, PURGE_BATCH);
  }
}
