// Drive: Google-Drive-like per-user cloud storage. Bytes live in R2 under drive/<owner_id>/<file_id>;
// the folder tree is D1 metadata (drive_nodes), so rename/move never copies data (R2 has no rename).
// The switch is per domain; a user has Drive when any of their domains enables it, and the storage
// pool is one per user across domains. Quota: per-user override, else the largest default among the
// user's enabled domains, hard-capped at 10 GB. Sharing: one link per folder, viewer/editor, only for
// signed-in users sharing at least one domain with the owner.
//
// 网盘:Google Drive 风格的每用户云存储。字节存 R2 的 drive/<owner_id>/<file_id>;
// 目录树是 D1 元数据(drive_nodes),改名/移动不搬数据(R2 没有重命名)。
// 开关按域名;用户所属任一域名开启即可用,存储跨域名同一份。
// 配额:用户单独指定优先,否则取其已开启域名中最大的默认值,硬顶 10TB。
// 共享:每文件夹一条链接,查看者/编辑者两档,仅限与所有者至少同属一个域名的登录用户。
import { Hono } from 'hono';
import type { Env, User } from './types';
import { HttpError } from './errors';
import { requireAuth } from './auth';
import { audit } from './audit';
import { now, randomToken, uid } from './util';
import { adminScope, checkDomainScope } from './admin';

const MB = 1024 * 1024;
export const DRIVE_HARD_CAP_MB = 10 * 1024 * 1024; // absolute per-user ceiling / 每用户绝对上限(10TB)
const SINGLE_MAX = 90 * MB;             // bigger uploads must go multipart / 超过必须走分片
const PART_SIZE = 32 * MB;              // suggested slice for the client / 建议前端的分片大小
const NAME_MAX = 255;
const DEPTH_MAX = 64;                   // folder nesting ceiling (also caps the recursive CTEs) / 目录深度上限(同时封顶递归查询)
const LIST_LIMIT = 1000;
const PURGE_BATCH = 300;                // permanent deletes per request, like mailbox purge / 每次请求彻底删除的节点数(同邮箱清空的思路)
const TRASH_KEEP_MS = 30 * 24 * 3600 * 1000;
const UPLOAD_STALE_MS = 24 * 3600 * 1000;
// Thumbnails: generated by the uploading client (WebP), stored beside the original
// 缩略图:由上传端生成(WebP),存在原文件 R2 键旁边
const THUMB_SUFFIX = '.t';
const THUMB_MAX_BYTES = 100 * 1024;

// Inline preview whitelist: nothing here may execute script under our origin. SVG and HTML must
// never enter this set (same trap the /cid endpoint once fell into); text/plain is pinned to UTF-8.
// 内联预览白名单:进这张表的类型都不能在本站源执行脚本。SVG 与 HTML 绝不能加进来
// (/cid 端点栽过的同一个坑);text/plain 强制 UTF-8。
const INLINE_MIMES = new Set([
  'image/png', 'image/jpeg', 'image/jpg', 'image/gif', 'image/webp', 'image/bmp', 'image/avif',
  'application/pdf', 'text/plain',
  'video/mp4', 'video/webm', 'video/ogg', 'video/quicktime',
  'audio/mpeg', 'audio/mp3', 'audio/mp4', 'audio/ogg', 'audio/wav', 'audio/x-wav', 'audio/webm',
  'audio/flac', 'audio/aac', 'audio/x-m4a',
]);

type Ctx = { Bindings: Env; Variables: { user: User; dq: Quota } };

interface Quota {
  enabled: boolean;
  quota: number; // bytes
  used: number;  // bytes
}

interface NodeRow {
  id: string;
  owner_id: string;
  parent_id: string | null;
  kind: 'folder' | 'file';
  name: string;
  mime: string;
  size: number;
  r2_key: string | null;
  starred: number;
  trashed: number;
  trashed_at: number | null;
  has_thumb: number;
  tree_bytes: number;
  created_at: number;
  updated_at: number;
}

// ---------- Quota and feature gate ----------
// ---------- 配额与功能开关 ----------

/** Effective quota and usage. enabled=false when none of the user's domains has Drive switched on.
 *  生效配额与用量。用户所属域名都没开网盘时 enabled=false。 */
export async function driveQuota(env: Env, userId: string): Promise<Quota> {
  const row = await env.DB.prepare(
    `SELECT u.drive_quota_mb AS user_mb, u.drive_bytes AS used,
       (SELECT MAX(d.drive_quota_mb) FROM domains d WHERE d.drive_enabled=1 AND d.id IN
         (SELECT mb.domain_id FROM grants g JOIN mailboxes mb ON mb.id=g.mailbox_id WHERE g.user_id=u.id)) AS dom_mb
     FROM users u WHERE u.id=?1`
  ).bind(userId).first<any>();
  const enabled = !!row && row.dom_mb != null;
  const mb = Math.min(row?.user_mb ?? row?.dom_mb ?? 0, DRIVE_HARD_CAP_MB);
  return { enabled, quota: mb * MB, used: row?.used || 0 };
}

/** Room for `add` more bytes in the owner's drive -- the owner's, not the uploader's: files created
 *  in a shared folder are charged to the folder owner.
 *  校验所有者还装得下 add 字节 —— 是所有者、不是操作者:传进共享文件夹的文件记在文件夹所有者的配额上。 */
async function checkQuota(env: Env, ownerId: string, add: number): Promise<void> {
  const q = await driveQuota(env, ownerId);
  if (!q.enabled) throw new HttpError(403, 'e_drive_disabled');
  if (q.used + add > q.quota) throw new HttpError(413, 'e_drive_quota');
}

// ---------- Tree and permission helpers ----------
// ---------- 目录树与权限 ----------

/** The node and all its ancestors, node first, root last. Empty when the id does not exist.
 *  节点及其全部祖先,节点在前、根在后。id 不存在时为空。 */
async function chainOf(env: Env, nodeId: string): Promise<NodeRow[]> {
  const rows = await env.DB.prepare(
    `WITH RECURSIVE chain AS (
       SELECT n.*, 0 AS depth FROM drive_nodes n WHERE n.id=?1
       UNION ALL
       SELECT p.*, c.depth+1 FROM drive_nodes p JOIN chain c ON p.id=c.parent_id WHERE c.depth<${DEPTH_MAX}
     ) SELECT * FROM chain ORDER BY depth`
  ).bind(nodeId).all();
  return (rows.results || []) as unknown as NodeRow[];
}

interface Access {
  node: NodeRow;
  level: 'owner' | 'editor' | 'viewer';
  /** For share members, the highest shared ancestor -- their movements stay inside this subtree.
   *  共享成员可见范围的顶点 —— 他们的一切操作都被圈在这棵子树里。 */
  shareRoot: string | null;
  chain: NodeRow[];
}

/** Resolve what the current user may do with a node. Owners always pass (even in the trash);
 *  others need a share membership on some ancestor, and anything inside the owner's trash is
 *  invisible to them. Missing and forbidden both answer 404, to not leak existence.
 *  解析当前用户对节点的权限。所有者永远放行(含回收站);其他人需要在某个祖先上有共享成员资格,
 *  且所有者回收站里的内容对他们一律不可见。不存在与无权限统一回 404,不泄露存在性。 */
async function accessNode(c: any, nodeId: string, need: 'view' | 'edit' | 'owner'): Promise<Access> {
  const user: User = c.get('user');
  const chain = await chainOf(c.env, nodeId);
  if (!chain.length) throw new HttpError(404, 'e_drive_not_found');
  const node = chain[0];
  if (node.owner_id === user.id) return { node, level: 'owner', shareRoot: null, chain };
  if (need === 'owner') throw new HttpError(404, 'e_drive_not_found');
  if (chain.some((n) => n.trashed)) throw new HttpError(404, 'e_drive_not_found');
  const ids = chain.map((n) => n.id);
  const rows = await c.env.DB.prepare(
    `SELECT s.node_id, s.role FROM drive_shares s JOIN drive_share_members m ON m.share_id=s.id
     WHERE m.user_id=?1 AND s.node_id IN (${ids.map((_, i) => '?' + (i + 2)).join(',')})`
  ).bind(user.id, ...ids).all();
  const hits = (rows.results || []) as { node_id: string; role: string }[];
  if (!hits.length) throw new HttpError(404, 'e_drive_not_found');
  const level = hits.some((h) => h.role === 'editor') ? 'editor' : 'viewer';
  if (need === 'edit' && level !== 'editor') throw new HttpError(403, 'e_drive_forbidden');
  // Among qualifying shares pick the one closest to the root: the widest subtree
  // 命中多个共享时取离根最近的那个:活动范围最大
  const best = hits
    .filter((h) => level === 'viewer' || h.role === 'editor')
    .sort((a, b) => ids.indexOf(b.node_id) - ids.indexOf(a.node_id))[0];
  return { node, level, shareRoot: best.node_id, chain };
}

function cleanName(v: unknown): string {
  // Control characters and '/' out; everything else (any script) is welcome
  // 去掉控制字符与 '/',其余(任意文字)都放行
  const s = String(v ?? '').replace(/[\u0000-\u001f\u007f/]/g, '').trim();
  if (!s || s.length > NAME_MAX) throw new HttpError(400, 'e_drive_bad_name');
  return s;
}

function cleanMime(v: unknown): string {
  const s = String(v ?? '').toLowerCase().split(';')[0].trim();
  return /^[a-z0-9.+-]+\/[a-z0-9.+-]+$/.test(s) ? s.slice(0, 120) : 'application/octet-stream';
}

function nodeJson(n: any, withShared = true) {
  return {
    id: n.id, parent_id: n.parent_id || null, kind: n.kind, name: n.name, mime: n.mime || '',
    size: n.size || 0, tree_bytes: n.tree_bytes || 0, starred: !!n.starred, trashed: !!n.trashed,
    shared: withShared ? !!n.shared : false, thumb: !!n.has_thumb,
    created_at: n.created_at, updated_at: n.updated_at,
  };
}

/** Ancestor-chain rollup for the materialised folder sizes: one statement, O(depth) rows.
 *  Deltas are plain commutative increments, so any interleaving of concurrent operations
 *  lands on the same totals. Propagation stops at a trashed ancestor: everything above it
 *  already dropped that subtree's contribution when the ancestor was trashed (matters when a
 *  node inside a trashed folder is trashed individually via the API). Returns null when there
 *  is nothing to do.
 *  物化文件夹大小的祖先链上卷。一条语句,O(深度) 行。增量是可交换的加法,并发操作任意交错
 *  结果都一致。传播在已回收祖先处停止:其上层早在该祖先进回收站时就扣掉了整棵子树的贡献
 *  (对"经 API 单独回收已回收文件夹内的节点"这种路径至关重要)。无事可做时返回 null。 */
function ancDelta(env: Env, parentId: string | null | undefined, delta: number): D1PreparedStatement | null {
  if (!parentId || !delta) return null;
  return env.DB.prepare(
    `WITH RECURSIVE anc(id, depth) AS (
       SELECT ?1, 0
       UNION ALL SELECT n.parent_id, a.depth+1 FROM drive_nodes n JOIN anc a ON n.id=a.id
       WHERE n.parent_id IS NOT NULL AND n.trashed=0 AND a.depth<${DEPTH_MAX}
     ) UPDATE drive_nodes SET tree_bytes=MAX(tree_bytes+?2,0) WHERE kind='folder' AND id IN (SELECT id FROM anc)`
  ).bind(parentId, delta);
}

/** The bytes a node contributes to its ancestors: its own size, or its materialised subtree
 *  本节点为祖先贡献的字节数:文件是自身大小,文件夹是其物化子树大小 */
const nodeBytes = (n: NodeRow | any): number => (n.kind === 'file' ? n.size || 0 : n.tree_bytes || 0);

/** Where a create/upload lands: the user's own root, or a folder they can edit (their own or a
 *  shared one -- then the folder owner's drive takes the file). Nothing lands inside a trash.
 *  新建/上传落到哪里:自己的根目录,或一个有编辑权的文件夹(自己的或共享的 —— 后者落入文件夹
 *  所有者的网盘)。回收站里不允许落任何东西。 */
async function resolveWriteTarget(c: any, parent: string): Promise<{ ownerId: string; parentId: string | null }> {
  if (parent === 'root' || !parent) return { ownerId: (c.get('user') as User).id, parentId: null };
  const a = await accessNode(c, parent, 'edit');
  if (a.node.kind !== 'folder') throw new HttpError(400, 'e_drive_not_folder');
  if (a.chain.some((n) => n.trashed)) throw new HttpError(400, 'e_drive_trashed');
  if (a.chain.length >= DEPTH_MAX - 1) throw new HttpError(400, 'e_drive_too_deep');
  return { ownerId: a.node.owner_id, parentId: a.node.id };
}

/** The Drive forbids duplicate names per folder and kind. This finds the standing occupant of a
 *  name so uploads can overwrite it and renames can refuse it. Ranked newest-first because
 *  legacy data may still hold duplicates from before the rule.
 *  网盘按目录和类型禁止重名。此函数找出当前占着某个名字的节点。上传用它来覆盖,
 *  改名用它来拒绝。按最新排序,因为规则之前的存量数据可能已有重名。 */
async function findClash(env: Env, ownerId: string, parentId: string | null, name: string, kind: string): Promise<NodeRow | null> {
  const sql = parentId
    ? 'SELECT * FROM drive_nodes WHERE owner_id=?1 AND parent_id=?2 AND name=?3 AND kind=?4 AND trashed=0 ORDER BY updated_at DESC LIMIT 1'
    : 'SELECT * FROM drive_nodes WHERE owner_id=?1 AND parent_id IS NULL AND name=?2 AND kind=?3 AND trashed=0 ORDER BY updated_at DESC LIMIT 1';
  const binds = parentId ? [ownerId, parentId, name, kind] : [ownerId, name, kind];
  const row = await env.DB.prepare(sql).bind(...binds).first();
  return (row as unknown as NodeRow) || null;
}

/** Drop rows whose ancestors include a trashed folder (used by search/starred/recent, where the
 *  query alone cannot see implicit trash membership). Chain lookups are memoised per parent.
 *  过滤掉祖先在回收站里的行(搜索/星标/最近用 —— 单条查询看不出"隐式在回收站")。按父节点缓存。 */
async function dropTrashedAncestors(env: Env, rows: any[]): Promise<any[]> {
  const bad = new Map<string, boolean>();
  const out: any[] = [];
  for (const r of rows) {
    if (r.trashed) continue;
    if (!r.parent_id) { out.push(r); continue; }
    if (!bad.has(r.parent_id)) {
      const chain = await chainOf(env, r.parent_id);
      let b = !chain.length;
      for (let i = chain.length - 1; i >= 0; i--) {
        b = b || !!chain[i].trashed;
        bad.set(chain[i].id, b);
      }
      if (!chain.length) bad.set(r.parent_id, true);
    }
    if (!bad.get(r.parent_id)) out.push(r);
  }
  return out;
}

/** Permanently delete up to `limit` nodes of the subtree at rootId, deepest first (children always
 *  go before their parent, so an interrupted run leaves a consistent tree). Removes R2 objects,
 *  share rows and refunds the owner's quota. Returns how many nodes remain.
 *  彻底删除以 rootId 为根的子树,一次最多 limit 个节点、最深的先删(孩子永远先于父亲,中断后树仍
 *  一致)。连带删 R2 对象与共享记录,并退还所有者配额。返回还剩多少节点。 */
export async function purgeSubtree(env: Env, rootId: string, limit = PURGE_BATCH): Promise<number> {
  const rows = await env.DB.prepare(
    `WITH RECURSIVE sub(id, depth) AS (
       SELECT id, 0 FROM drive_nodes WHERE id=?1
       UNION ALL SELECT n.id, s.depth+1 FROM drive_nodes n JOIN sub s ON n.parent_id=s.id WHERE s.depth<${DEPTH_MAX}
     ) SELECT n.id, n.kind, n.size, n.r2_key, n.owner_id FROM sub JOIN drive_nodes n ON n.id=sub.id
     ORDER BY sub.depth DESC`
  ).bind(rootId).all();
  const all = (rows.results || []) as any[];
  if (!all.length) return 0;
  const batch = all.slice(0, limit);
  // Each file may carry a thumbnail at <r2_key>.t -- delete it in the same sweep.
  // R2 bulk delete silently skips keys that do not exist.
  // 每个文件旁可能有 <r2_key>.t 的缩略图,同一批顺手删掉。R2 批量删除对不存在的键静默跳过。
  const keys = batch.flatMap((n) => (n.r2_key ? [n.r2_key, n.r2_key + THUMB_SUFFIX] : []));
  for (let i = 0; i < keys.length; i += 900) {
    await env.RAW.delete(keys.slice(i, i + 900)).catch(() => {});
  }
  const freed = batch.reduce((s, n) => s + (n.kind === 'file' ? n.size || 0 : 0), 0);
  const stmts: D1PreparedStatement[] = [];
  for (let i = 0; i < batch.length; i += 90) {
    const part = batch.slice(i, i + 90).map((n) => n.id);
    const ph = part.map((_, j) => '?' + (j + 1)).join(',');
    // Members must go before their shares (the subquery still needs the share rows)
    // 成员先于共享删(子查询还要用到共享行)
    stmts.push(env.DB.prepare(
      `DELETE FROM drive_share_members WHERE share_id IN (SELECT id FROM drive_shares WHERE node_id IN (${ph}))`
    ).bind(...part));
    stmts.push(env.DB.prepare(`DELETE FROM drive_shares WHERE node_id IN (${ph})`).bind(...part));
    stmts.push(env.DB.prepare(`DELETE FROM drive_nodes WHERE id IN (${ph})`).bind(...part));
  }
  if (freed > 0) {
    stmts.push(env.DB.prepare('UPDATE users SET drive_bytes=MAX(drive_bytes-?1,0) WHERE id=?2').bind(freed, batch[0].owner_id));
  }
  await env.DB.batch(stmts);
  return all.length - batch.length;
}

// ---------- User-facing API (/api/drive) ----------
// ---------- 用户侧 API(/api/drive) ----------

export const driveApp = new Hono<Ctx>();

// In-isolate short-lived caches for the media streaming hot path. A video seek fires a fresh
// Range request, and each one was paying two to three SEQUENTIAL D1 round trips (quota gate,
// ancestor-chain access CTE, share membership) before R2 produced a single byte. Worker
// isolates live across requests, so a 60-second memory cache absorbs the burst that scrubbing
// the timeline generates. Scope: read-only file streaming; everything that mutates or displays
// live numbers keeps querying fresh. Revoking a share can lag a playing stream by up to 60s;
// deletes do not (R2 is already empty and answers 404).
// 流媒体热路径的 isolate 内存短时缓存。每次视频 seek 都是一个新的 Range 请求,
// 之前每个都要串行付 2-3 个 D1 往返(配额闸、祖先链权限 CTE、共享成员)之后 R2 才出第一个字节。
// Worker isolate 跨请求存活,60 秒的内存缓存正好吸收拖进度条产生的这阵请求风暴。
// 只作用于只读的文件流。所有写操作与实时数字仍然现查。撤销共享对正在播的流最多延迟 60 秒;
// 删除不受此影响(R2 已空,直接 404)。
const STREAM_TTL = 60 * 1000;
const quotaCache = new Map<string, { q: Quota; exp: number }>();
const accessCache = new Map<string, { node: NodeRow; exp: number }>();
const sweep = (m: Map<string, unknown>) => {
  if (m.size > 500) m.clear();
};

const isStreamRead = (c: any) => c.req.method === 'GET' && String(c.req.path || '').includes('/files/');

driveApp.use('*', requireAuth);
driveApp.use('*', async (c, next) => {
  const uid2 = c.get('user').id;
  let q: Quota | null = null;
  if (isStreamRead(c)) {
    const hit = quotaCache.get(uid2);
    if (hit && hit.exp > Date.now()) q = hit.q;
  }
  if (!q) {
    q = await driveQuota(c.env, uid2);
    sweep(quotaCache);
    quotaCache.set(uid2, { q, exp: Date.now() + STREAM_TTL });
  }
  if (!q.enabled) throw new HttpError(403, 'e_drive_disabled');
  c.set('dq', q);
  await next();
});

/** View access for streaming endpoints, memoised per (user, node) for 60 seconds
 *  流端点的读权限。按用户与节点记忆 60 秒 */
async function accessFileCached(c: any, nodeId: string): Promise<NodeRow> {
  const key = (c.get('user') as User).id + ':' + nodeId;
  const hit = accessCache.get(key);
  if (hit && hit.exp > Date.now()) return hit.node;
  const a = await accessNode(c, nodeId, 'view');
  sweep(accessCache);
  accessCache.set(key, { node: a.node, exp: Date.now() + STREAM_TTL });
  return a.node;
}

driveApp.get('/state', (c) => {
  const q = c.get('dq');
  return c.json({ used: q.used, quota: q.quota, single_max: SINGLE_MAX, part_size: PART_SIZE, trash_days: 30 });
});

driveApp.get('/list', async (c) => {
  const parent = String(c.req.query('parent') || 'root');
  const user = c.get('user');
  const childrenSql = (where: string) =>
    `SELECT n.*, (SELECT 1 FROM drive_shares s WHERE s.node_id=n.id) AS shared
     FROM drive_nodes n WHERE ${where} AND n.trashed=0
     ORDER BY n.kind='folder' DESC, n.name COLLATE NOCASE LIMIT ${LIST_LIMIT}`;
  if (parent === 'root') {
    const rows = await c.env.DB.prepare(childrenSql('n.owner_id=?1 AND n.parent_id IS NULL')).bind(user.id).all();
    return c.json({
      access: 'owner', share_root: null, path: [],
      nodes: (rows.results || []).map((n) => nodeJson(n)),
    });
  }
  const a = await accessNode(c, parent, 'view');
  if (a.node.kind !== 'folder') throw new HttpError(400, 'e_drive_not_folder');
  const rows = await c.env.DB.prepare(childrenSql('n.parent_id=?1')).bind(a.node.id).all();
  // Breadcrumbs: the owner sees the full path; a share member's path stops at the share root
  // 面包屑:所有者看全路径;共享成员只能看到共享顶点以下
  let path = a.chain.slice().reverse();
  if (a.shareRoot) path = path.slice(path.findIndex((n) => n.id === a.shareRoot));
  return c.json({
    access: a.level, share_root: a.shareRoot,
    // Owners may browse folders that sit in the trash; the UI switches to trash-style actions
    // 所有者可以浏览回收站里的文件夹;界面据此切换成回收站式的操作
    in_trash: a.chain.some((n) => n.trashed),
    path: path.map((n) => ({ id: n.id, name: n.name })),
    nodes: (rows.results || []).map((n) => nodeJson(n, a.level === 'owner')),
  });
});

driveApp.get('/search', async (c) => {
  const q = String(c.req.query('q') || '').trim().slice(0, 100);
  if (!q) return c.json({ nodes: [] });
  const like = '%' + q.replace(/[\\%_]/g, (ch) => '\\' + ch) + '%';
  const rows = await c.env.DB.prepare(
    `SELECT n.*, (SELECT 1 FROM drive_shares s WHERE s.node_id=n.id) AS shared FROM drive_nodes n
     WHERE n.owner_id=?1 AND n.trashed=0 AND n.name LIKE ?2 ESCAPE '\\'
     ORDER BY n.updated_at DESC LIMIT 200`
  ).bind(c.get('user').id, like).all();
  const vis = await dropTrashedAncestors(c.env, rows.results || []);
  return c.json({ nodes: vis.map((n) => nodeJson(n)) });
});

driveApp.get('/starred', async (c) => {
  const rows = await c.env.DB.prepare(
    `SELECT n.*, (SELECT 1 FROM drive_shares s WHERE s.node_id=n.id) AS shared FROM drive_nodes n
     WHERE n.owner_id=?1 AND n.starred=1 AND n.trashed=0
     ORDER BY n.kind='folder' DESC, n.name COLLATE NOCASE LIMIT ${LIST_LIMIT}`
  ).bind(c.get('user').id).all();
  const vis = await dropTrashedAncestors(c.env, rows.results || []);
  return c.json({ nodes: vis.map((n) => nodeJson(n)) });
});

driveApp.get('/recent', async (c) => {
  const rows = await c.env.DB.prepare(
    `SELECT n.*, (SELECT 1 FROM drive_shares s WHERE s.node_id=n.id) AS shared FROM drive_nodes n
     WHERE n.owner_id=?1 AND n.kind='file' AND n.trashed=0 ORDER BY n.updated_at DESC LIMIT 80`
  ).bind(c.get('user').id).all();
  const vis = (await dropTrashedAncestors(c.env, rows.results || [])).slice(0, 50);
  return c.json({ nodes: vis.map((n) => nodeJson(n)) });
});

driveApp.get('/trash', async (c) => {
  const rows = await c.env.DB.prepare(
    `SELECT * FROM drive_nodes WHERE owner_id=?1 AND trashed=1 ORDER BY trashed_at DESC LIMIT ${LIST_LIMIT}`
  ).bind(c.get('user').id).all();
  return c.json({ nodes: (rows.results || []).map((n) => nodeJson(n, false)) });
});

driveApp.post('/folders', async (c) => {
  const body = await c.req.json<any>();
  const name = cleanName(body.name);
  const target = await resolveWriteTarget(c, String(body.parent || 'root'));
  // No duplicate names: an existing folder of the same name IS the result (merge semantics --
  // re-uploading a directory lands in the same tree instead of minting a twin)
  // 禁止重名。已有同名文件夹就直接作为结果返回(合并语义 —— 目录重传落回同一棵树,
  // 不再造出双胞胎)
  const clash = await findClash(c.env, target.ownerId, target.parentId, name, 'folder');
  if (clash) return c.json(nodeJson(clash));
  const id = uid();
  const t = now();
  await c.env.DB.prepare(
    `INSERT INTO drive_nodes (id, owner_id, parent_id, kind, name, created_at, updated_at) VALUES (?1,?2,?3,'folder',?4,?5,?5)`
  ).bind(id, target.ownerId, target.parentId, name, t).run();
  return c.json(nodeJson({ id, parent_id: target.parentId, kind: 'folder', name, created_at: t, updated_at: t }));
});

driveApp.post('/nodes/:id/rename', async (c) => {
  const a = await accessNode(c, c.req.param('id'), 'edit');
  if (a.chain.some((n) => n.trashed)) throw new HttpError(400, 'e_drive_trashed');
  if (a.level !== 'owner' && a.node.id === a.shareRoot) throw new HttpError(403, 'e_drive_forbidden');
  const name = cleanName((await c.req.json<any>()).name);
  // Renaming onto an occupied name is refused -- overwrite semantics belong to uploads only
  // 改名撞上已占用的名字直接拒绝。覆盖语义只属于上传
  const clash = await findClash(c.env, a.node.owner_id, a.node.parent_id, name, a.node.kind);
  if (clash && clash.id !== a.node.id) throw new HttpError(409, 'e_drive_name_taken');
  await c.env.DB.prepare('UPDATE drive_nodes SET name=?1, updated_at=?2 WHERE id=?3').bind(name, now(), a.node.id).run();
  return c.json({ ok: true, name });
});

driveApp.post('/nodes/:id/star', async (c) => {
  const a = await accessNode(c, c.req.param('id'), 'owner');
  const on = (await c.req.json<any>()).starred ? 1 : 0;
  await c.env.DB.prepare('UPDATE drive_nodes SET starred=?1 WHERE id=?2').bind(on, a.node.id).run();
  return c.json({ ok: true, starred: !!on });
});

driveApp.post('/nodes/:id/move', async (c) => {
  const a = await accessNode(c, c.req.param('id'), 'edit');
  if (a.chain.some((n) => n.trashed)) throw new HttpError(400, 'e_drive_trashed');
  if (a.level !== 'owner' && a.node.id === a.shareRoot) throw new HttpError(403, 'e_drive_forbidden');
  const parent = String((await c.req.json<any>()).parent || 'root');
  let parentId: string | null;
  if (parent === 'root') {
    // Only the owner has a root here; an editor's own root is a different drive
    // 根目录只属于所有者;编辑者的根是另一个人的网盘
    if (a.level !== 'owner') throw new HttpError(403, 'e_drive_forbidden');
    parentId = null;
  } else {
    const t = await accessNode(c, parent, 'edit');
    if (t.node.kind !== 'folder') throw new HttpError(400, 'e_drive_not_folder');
    if (t.chain.some((n) => n.trashed)) throw new HttpError(400, 'e_drive_trashed');
    // No ownership transfer: source and target must live in the same drive
    // 不做所有权转移:源与目标必须在同一个人的网盘里
    if (t.node.owner_id !== a.node.owner_id) throw new HttpError(400, 'e_drive_cross_drive');
    if (t.chain.some((n) => n.id === a.node.id)) throw new HttpError(400, 'e_drive_cycle');
    if (t.chain.length + 1 >= DEPTH_MAX) throw new HttpError(400, 'e_drive_too_deep');
    parentId = t.node.id;
  }
  // The destination must not already hold this name / 目的地不能已有同名条目
  const clash = await findClash(c.env, a.node.owner_id, parentId, a.node.name, a.node.kind);
  if (clash && clash.id !== a.node.id) throw new HttpError(409, 'e_drive_name_taken');
  {
    const stmts = [
      c.env.DB.prepare('UPDATE drive_nodes SET parent_id=?1, updated_at=?2 WHERE id=?3')
        .bind(parentId, now(), a.node.id),
    ];
    // Old chain loses the bytes, new chain gains them; a shared prefix nets to zero by itself
    // 旧链减、新链加。公共前缀一减一加自动归零,无需特判
    if (parentId !== a.node.parent_id) {
      const bytes = nodeBytes(a.node);
      const sub = ancDelta(c.env, a.node.parent_id, -bytes);
      const add = ancDelta(c.env, parentId, bytes);
      if (sub) stmts.push(sub);
      if (add) stmts.push(add);
    }
    await c.env.DB.batch(stmts);
  }
  return c.json({ ok: true });
});

driveApp.post('/nodes/:id/trash', async (c) => {
  const a = await accessNode(c, c.req.param('id'), 'edit');
  if (a.level !== 'owner' && a.node.id === a.shareRoot) throw new HttpError(403, 'e_drive_forbidden');
  if (!a.node.trashed) {
    const t = now();
    const stmts = [
      c.env.DB.prepare('UPDATE drive_nodes SET trashed=1, trashed_at=?1, updated_at=?1 WHERE id=?2')
        .bind(t, a.node.id),
    ];
    // A folder's own tree_bytes IS its contribution -- no recursive sum ever needed
    // 文件夹自己的 tree_bytes 就是它的贡献量,永远不用递归求和
    const ad = ancDelta(c.env, a.node.parent_id, -nodeBytes(a.node));
    if (ad) stmts.push(ad);
    await c.env.DB.batch(stmts);
  }
  return c.json({ ok: true });
});

driveApp.post('/nodes/:id/restore', async (c) => {
  const a = await accessNode(c, c.req.param('id'), 'owner');
  if (!a.node.trashed) throw new HttpError(400, 'e_drive_not_trashed');
  // If the original spot is gone or itself in the trash, restore to the root instead
  // 原位置没了或也在回收站里,就还原到根目录
  let parentId = a.node.parent_id;
  if (parentId) {
    const chain = await chainOf(c.env, parentId);
    if (!chain.length || chain.some((n) => n.trashed)) parentId = null;
  }
  {
    const stmts = [
      c.env.DB.prepare('UPDATE drive_nodes SET trashed=0, trashed_at=NULL, parent_id=?1, updated_at=?2 WHERE id=?3')
        .bind(parentId, now(), a.node.id),
    ];
    const ad = ancDelta(c.env, parentId, nodeBytes(a.node));
    if (ad) stmts.push(ad);
    await c.env.DB.batch(stmts);
  }
  return c.json({ ok: true });
});

driveApp.delete('/nodes/:id', async (c) => {
  const a = await accessNode(c, c.req.param('id'), 'owner');
  if (!a.node.trashed) throw new HttpError(400, 'e_drive_not_trashed');
  const remaining = await purgeSubtree(c.env, a.node.id);
  return c.json({ remaining });
});

driveApp.post('/trash/empty', async (c) => {
  const user = c.get('user');
  const row = await c.env.DB.prepare(
    'SELECT id FROM drive_nodes WHERE owner_id=?1 AND trashed=1 LIMIT 1'
  ).bind(user.id).first<any>();
  if (row) await purgeSubtree(c.env, row.id);
  const left = await c.env.DB.prepare(
    'SELECT COUNT(*) AS n FROM drive_nodes WHERE owner_id=?1 AND trashed=1'
  ).bind(user.id).first<any>();
  return c.json({ remaining: left?.n || 0 });
});

// ---------- Upload ----------
// ---------- 上传 ----------

// Small files in one request: raw body, metadata in the query string
// 小文件一次请求:原始字节做 body,元数据放查询串
driveApp.post('/upload', async (c) => {
  const target = await resolveWriteTarget(c, String(c.req.query('parent') || 'root'));
  const name = cleanName(c.req.query('name'));
  const mime = cleanMime(c.req.query('mime'));
  const len = parseInt(c.req.header('Content-Length') || '', 10);
  if (!c.req.raw.body || !Number.isFinite(len) || len < 0) throw new HttpError(400, 'e_drive_body_required');
  if (len > SINGLE_MAX) throw new HttpError(413, 'e_drive_part_too_big');
  // An occupied name means overwrite: same node id, same R2 key, new bytes. The put below
  // replaces the object atomically; star and creation date simply stay.
  // 名字被占用即覆盖。同一节点 id、同一 R2 键、换新字节。下面的 put 原子替换对象,
  // 星标与创建时间自然保留。
  const clash = await findClash(c.env, target.ownerId, target.parentId, name, 'file');
  const oldSize = clash?.size || 0;
  const q0 = await driveQuota(c.env, target.ownerId);
  if (!q0.enabled) throw new HttpError(403, 'e_drive_disabled');
  if (q0.used - oldSize + len > q0.quota) throw new HttpError(413, 'e_drive_quota');
  const id = clash ? clash.id : uid();
  const key = clash?.r2_key || `drive/${target.ownerId}/${id}`;
  const obj = await c.env.RAW.put(key, c.req.raw.body, { httpMetadata: { contentType: mime } });
  const size = obj?.size ?? len;
  const t = now();
  if (clash) {
    // The stale thumbnail dies with the old bytes / 旧缩略图随旧内容一起作废
    await c.env.RAW.delete(key + THUMB_SUFFIX).catch(() => {});
    const stmts = [
      c.env.DB.prepare('UPDATE drive_nodes SET mime=?1, size=?2, has_thumb=0, updated_at=?3 WHERE id=?4')
        .bind(mime, size, t, id),
      c.env.DB.prepare('UPDATE users SET drive_bytes=MAX(drive_bytes+?1,0) WHERE id=?2')
        .bind(size - oldSize, target.ownerId),
    ];
    const ad = ancDelta(c.env, target.parentId, size - oldSize);
    if (ad) stmts.push(ad);
    await c.env.DB.batch(stmts);
    return c.json(nodeJson({ ...clash, mime, size, has_thumb: 0, updated_at: t, tree_bytes: clash.tree_bytes }));
  }
  // Re-check with the actual byte count; concurrent uploads may both have passed the pre-check
  // 用实际字节数复核一次;并发上传可能都通过了预检
  const q = await driveQuota(c.env, target.ownerId);
  if (q.used + size > q.quota) {
    await c.env.RAW.delete(key).catch(() => {});
    throw new HttpError(413, 'e_drive_quota');
  }
  {
    const stmts = [
      c.env.DB.prepare(
        `INSERT INTO drive_nodes (id, owner_id, parent_id, kind, name, mime, size, r2_key, created_at, updated_at)
         VALUES (?1,?2,?3,'file',?4,?5,?6,?7,?8,?8)`
      ).bind(id, target.ownerId, target.parentId, name, mime, size, key, t),
      c.env.DB.prepare('UPDATE users SET drive_bytes=drive_bytes+?1 WHERE id=?2').bind(size, target.ownerId),
    ];
    const ad = ancDelta(c.env, target.parentId, size);
    if (ad) stmts.push(ad);
    await c.env.DB.batch(stmts);
  }
  return c.json(nodeJson({ id, parent_id: target.parentId, kind: 'file', name, mime, size, created_at: t, updated_at: t }));
});

// Large files go through R2 multipart. The server keeps the declared size and target on its own
// authority (drive_uploads) instead of trusting the complete call; stale rows are aborted hourly.
// 大文件走 R2 分片。声明的大小与落点由服务端自己记(drive_uploads),不信 complete 请求;
// 过期未完成的由小时级 cron 中止。
driveApp.post('/upload/init', async (c) => {
  const body = await c.req.json<any>();
  const target = await resolveWriteTarget(c, String(body.parent || 'root'));
  const name = cleanName(body.name);
  const mime = cleanMime(body.mime);
  const size = Math.floor(Number(body.size));
  if (!Number.isFinite(size) || size <= 0) throw new HttpError(400, 'e_drive_body_required');
  await checkQuota(c.env, target.ownerId, size);
  const id = uid();
  const key = `drive/${target.ownerId}/${id}`;
  const mp = await c.env.RAW.createMultipartUpload(key, { httpMetadata: { contentType: mime } });
  await c.env.DB.prepare(
    `INSERT INTO drive_uploads (id, user_id, owner_id, parent_id, name, mime, size, r2_key, upload_id, created_at)
     VALUES (?1,?2,?3,?4,?5,?6,?7,?8,?9,?10)`
  ).bind(id, c.get('user').id, target.ownerId, target.parentId, name, mime, size, key, mp.uploadId, now()).run();
  return c.json({ id, part_size: PART_SIZE });
});

async function getUpload(c: any): Promise<any> {
  const u = await c.env.DB.prepare('SELECT * FROM drive_uploads WHERE id=?1 AND user_id=?2')
    .bind(c.req.param('id'), (c.get('user') as User).id).first();
  if (!u) throw new HttpError(404, 'e_drive_upload_missing');
  return u;
}

driveApp.put('/upload/:id/part', async (c) => {
  const u = await getUpload(c);
  const n = parseInt(c.req.query('n') || '', 10);
  if (!Number.isFinite(n) || n < 1 || n > 10000) throw new HttpError(400, 'e_bad_request');
  const len = parseInt(c.req.header('Content-Length') || '', 10);
  if (!c.req.raw.body || !Number.isFinite(len) || len <= 0) throw new HttpError(400, 'e_drive_body_required');
  if (len > SINGLE_MAX) throw new HttpError(413, 'e_drive_part_too_big');
  const mpu = c.env.RAW.resumeMultipartUpload(u.r2_key, u.upload_id);
  const part = await mpu.uploadPart(n, c.req.raw.body as any);
  return c.json({ n: part.partNumber, etag: part.etag });
});

driveApp.post('/upload/:id/complete', async (c) => {
  const u = await getUpload(c);
  const body = await c.req.json<any>();
  const parts = (Array.isArray(body.parts) ? body.parts : [])
    .map((p: any) => ({ partNumber: parseInt(p.n, 10), etag: String(p.etag || '') }))
    .filter((p: any) => Number.isFinite(p.partNumber) && p.etag);
  if (!parts.length) throw new HttpError(400, 'e_bad_request');
  const mpu = c.env.RAW.resumeMultipartUpload(u.r2_key, u.upload_id);
  let obj: R2Object;
  try {
    obj = await mpu.complete(parts);
  } catch (e) {
    await mpu.abort().catch(() => {});
    await c.env.DB.prepare('DELETE FROM drive_uploads WHERE id=?1').bind(u.id).run();
    throw new HttpError(400, 'e_drive_upload_failed');
  }
  // The target folder may have been trashed or purged while the upload ran -- fall back to the root
  // 上传期间目标文件夹可能已进回收站或被删 —— 回落到根目录
  let parentId = u.parent_id;
  if (parentId) {
    const chain = await chainOf(c.env, parentId);
    if (!chain.length || chain.some((x) => x.trashed) || chain[0].owner_id !== u.owner_id || chain[0].kind !== 'folder') {
      parentId = null;
    }
  }
  // Occupied name = overwrite: the old node and its bytes go away, the new node inherits the
  // star and the creation date.
  // 名字被占用即覆盖。旧节点连同其字节移除,新节点继承星标与创建时间。
  const clash = await findClash(c.env, u.owner_id, parentId, u.name, 'file');
  const q = await driveQuota(c.env, u.owner_id);
  if (q.used - (clash?.size || 0) + obj.size > q.quota) {
    await c.env.RAW.delete(u.r2_key).catch(() => {});
    await c.env.DB.prepare('DELETE FROM drive_uploads WHERE id=?1').bind(u.id).run();
    throw new HttpError(413, 'e_drive_quota');
  }
  const t = now();
  if (clash) {
    await c.env.RAW.delete([clash.r2_key!, clash.r2_key + THUMB_SUFFIX]).catch(() => {});
  }
  const stmts = [
    ...(clash ? [c.env.DB.prepare('DELETE FROM drive_nodes WHERE id=?1').bind(clash.id)] : []),
    c.env.DB.prepare(
      `INSERT INTO drive_nodes (id, owner_id, parent_id, kind, name, mime, size, r2_key, starred, created_at, updated_at)
       VALUES (?1,?2,?3,'file',?4,?5,?6,?7,?8,?9,?10)`
    ).bind(u.id, u.owner_id, parentId, u.name, u.mime, obj.size, u.r2_key,
      clash ? clash.starred : 0, clash ? clash.created_at : t, t),
    c.env.DB.prepare('UPDATE users SET drive_bytes=MAX(drive_bytes+?1,0) WHERE id=?2')
      .bind(obj.size - (clash?.size || 0), u.owner_id),
    c.env.DB.prepare('DELETE FROM drive_uploads WHERE id=?1').bind(u.id),
  ];
  // Overwrite replaces bytes under the same parent, so one net delta covers both
  // 覆盖发生在同一父目录下,一条净增量同时涵盖旧去新来
  const ad = ancDelta(c.env, parentId, obj.size - (clash?.size || 0));
  if (ad) stmts.push(ad);
  await c.env.DB.batch(stmts);
  return c.json(nodeJson({
    id: u.id, parent_id: parentId, kind: 'file', name: u.name, mime: u.mime, size: obj.size, created_at: t, updated_at: t,
  }));
});

driveApp.post('/upload/:id/abort', async (c) => {
  const u = await getUpload(c);
  try {
    await c.env.RAW.resumeMultipartUpload(u.r2_key, u.upload_id).abort();
  } catch {}
  await c.env.DB.prepare('DELETE FROM drive_uploads WHERE id=?1').bind(u.id).run();
  return c.json({ ok: true });
});

// ---------- Download ----------
// ---------- 下载 ----------

function parseRange(h: string | undefined): any {
  if (!h) return null;
  const m = /^bytes=(\d*)-(\d*)$/.exec(h.trim());
  if (!m || (!m[1] && !m[2])) return null;
  if (!m[1]) return { suffix: parseInt(m[2], 10) };
  const offset = parseInt(m[1], 10);
  if (!m[2]) return { offset };
  const end = parseInt(m[2], 10);
  if (end < offset) return null;
  return { offset, length: end - offset + 1 };
}

driveApp.get('/files/:id/dl', async (c) => {
  const node = await accessFileCached(c, c.req.param('id'));
  if (node.kind !== 'file' || !node.r2_key) throw new HttpError(400, 'e_drive_not_file');
  const range = parseRange(c.req.header('Range'));
  const obj: any = await c.env.RAW.get(node.r2_key, range ? { range } : undefined);
  if (!obj) throw new HttpError(404, 'e_drive_not_found');
  const mime = (node.mime || '').toLowerCase();
  const inline = c.req.query('inline') === '1' && INLINE_MIMES.has(mime);
  const h = new Headers();
  h.set('X-Content-Type-Options', 'nosniff');
  h.set('Accept-Ranges', 'bytes');
  h.set('Cache-Control', 'private, max-age=3600');
  h.set('ETag', `"${node.id}-${node.updated_at}"`);
  h.set('Content-Type', inline ? (mime === 'text/plain' ? 'text/plain; charset=utf-8' : mime) : mime || 'application/octet-stream');
  h.set('Content-Disposition', `${inline ? 'inline' : 'attachment'}; filename*=UTF-8''${encodeURIComponent(node.name)}`);
  if (range) {
    const r: any = obj.range || {};
    let off = 0;
    let len = obj.size;
    if (typeof r.offset === 'number') {
      off = r.offset;
      len = typeof r.length === 'number' ? r.length : obj.size - off;
    } else if (typeof r.suffix === 'number') {
      off = Math.max(0, obj.size - r.suffix);
      len = obj.size - off;
    }
    h.set('Content-Range', `bytes ${off}-${off + len - 1}/${obj.size}`);
    h.set('Content-Length', String(len));
    return new Response(obj.body, { status: 206, headers: h });
  }
  h.set('Content-Length', String(obj.size));
  return new Response(obj.body, { headers: h });
});

// ---------- Thumbnails ----------
// ---------- 缩略图 ----------

// The uploading client renders the thumbnail (image crop, video frame pick, PDF/text screenshot)
// and posts it here as WebP. The server only checks the magic bytes and the size cap -- and always
// serves the result as image/webp + nosniff, so a bogus "thumbnail" can never become same-origin
// script (the /cid lesson).
// 缩略图由上传端渲染(图片裁切、视频选帧、PDF/文本截图),以 WebP POST 到这里。服务端只验魔数
// 和大小上限 —— 且永远按 image/webp + nosniff 回出去,假"缩略图"成不了同源脚本(/cid 的教训)。
driveApp.post('/files/:id/thumb', async (c) => {
  const a = await accessNode(c, c.req.param('id'), 'edit');
  if (a.node.kind !== 'file' || !a.node.r2_key) throw new HttpError(400, 'e_drive_not_file');
  const len = parseInt(c.req.header('Content-Length') || '', 10);
  if (!Number.isFinite(len) || len <= 0) throw new HttpError(400, 'e_drive_body_required');
  if (len > THUMB_MAX_BYTES) throw new HttpError(413, 'e_drive_part_too_big');
  const buf = await c.req.arrayBuffer();
  if (buf.byteLength > THUMB_MAX_BYTES) throw new HttpError(413, 'e_drive_part_too_big');
  const b = new Uint8Array(buf);
  const tag = (o: number) => String.fromCharCode(b[o], b[o + 1], b[o + 2], b[o + 3]);
  if (b.length < 12 || tag(0) !== 'RIFF' || tag(8) !== 'WEBP') throw new HttpError(400, 'e_bad_request');
  await c.env.RAW.put(a.node.r2_key + THUMB_SUFFIX, buf, { httpMetadata: { contentType: 'image/webp' } });
  await c.env.DB.prepare('UPDATE drive_nodes SET has_thumb=1 WHERE id=?1').bind(a.node.id).run();
  // The uploader's own stream cache may still say has_thumb=0 / 上传者自己的流缓存可能还记着没有缩略图
  accessCache.delete(c.get('user').id + ':' + a.node.id);
  return c.json({ ok: true });
});

driveApp.get('/files/:id/thumb', async (c) => {
  const node = await accessFileCached(c, c.req.param('id'));
  if (node.kind !== 'file' || !node.r2_key || !node.has_thumb) {
    throw new HttpError(404, 'e_drive_not_found');
  }
  const obj: any = await c.env.RAW.get(node.r2_key + THUMB_SUFFIX);
  if (!obj) throw new HttpError(404, 'e_drive_not_found');
  return new Response(obj.body, {
    headers: {
      'Content-Type': 'image/webp',
      'Content-Length': String(obj.size),
      'X-Content-Type-Options': 'nosniff',
      'Cache-Control': 'private, max-age=86400',
    },
  });
});

// ---------- Sharing ----------
// ---------- 共享 ----------

/** Do the two users have at least one domain in common (each holding some mailbox there)?
 *  两个用户是否至少同属一个域名(各自在该域名下有邮箱)? */
async function sharesDomainWith(env: Env, ownerId: string, userId: string): Promise<boolean> {
  const row = await env.DB.prepare(
    `SELECT 1 AS ok FROM grants g1 JOIN mailboxes m1 ON m1.id=g1.mailbox_id
     WHERE g1.user_id=?1 AND m1.domain_id IN (
       SELECT m2.domain_id FROM grants g2 JOIN mailboxes m2 ON m2.id=g2.mailbox_id WHERE g2.user_id=?2)
     LIMIT 1`
  ).bind(ownerId, userId).first();
  return !!row;
}

const SHARE_ROLES = ['viewer', 'editor'];

driveApp.get('/nodes/:id/shares', async (c) => {
  const a = await accessNode(c, c.req.param('id'), 'owner');
  const s = await c.env.DB.prepare('SELECT * FROM drive_shares WHERE node_id=?1').bind(a.node.id).first<any>();
  if (!s) return c.json({ share: null });
  const members = await c.env.DB.prepare(
    `SELECT m.user_id, m.joined_at, u.name, u.email FROM drive_share_members m JOIN users u ON u.id=m.user_id
     WHERE m.share_id=?1 ORDER BY m.joined_at`
  ).bind(s.id).all();
  return c.json({
    share: { id: s.id, token: s.token, role: s.role, created_at: s.created_at, members: members.results || [] },
  });
});

driveApp.post('/nodes/:id/shares', async (c) => {
  const a = await accessNode(c, c.req.param('id'), 'owner');
  if (a.node.kind !== 'folder') throw new HttpError(400, 'e_drive_share_folder_only');
  if (a.chain.some((n) => n.trashed)) throw new HttpError(400, 'e_drive_trashed');
  const body = await c.req.json<any>();
  const role = SHARE_ROLES.includes(body.role) ? body.role : 'viewer';
  const exist = await c.env.DB.prepare('SELECT * FROM drive_shares WHERE node_id=?1').bind(a.node.id).first<any>();
  if (exist) return c.json({ id: exist.id, token: exist.token, role: exist.role, created_at: exist.created_at });
  const id = uid();
  const token = randomToken(24);
  const t = now();
  await c.env.DB.prepare(
    'INSERT INTO drive_shares (id, token, node_id, owner_id, role, created_at) VALUES (?1,?2,?3,?4,?5,?6)'
  ).bind(id, token, a.node.id, a.node.owner_id, role, t).run();
  return c.json({ id, token, role, created_at: t });
});

async function ownShare(c: any): Promise<any> {
  const s = await c.env.DB.prepare('SELECT * FROM drive_shares WHERE id=?1').bind(c.req.param('id')).first();
  if (!s || s.owner_id !== (c.get('user') as User).id) throw new HttpError(404, 'e_drive_share_not_found');
  return s;
}

driveApp.put('/shares/:id', async (c) => {
  const s = await ownShare(c);
  const role = String((await c.req.json<any>()).role || '');
  if (!SHARE_ROLES.includes(role)) throw new HttpError(400, 'e_bad_request');
  await c.env.DB.prepare('UPDATE drive_shares SET role=?1 WHERE id=?2').bind(role, s.id).run();
  return c.json({ ok: true });
});

driveApp.delete('/shares/:id', async (c) => {
  const s = await ownShare(c);
  await c.env.DB.batch([
    c.env.DB.prepare('DELETE FROM drive_share_members WHERE share_id=?1').bind(s.id),
    c.env.DB.prepare('DELETE FROM drive_shares WHERE id=?1').bind(s.id),
  ]);
  return c.json({ ok: true });
});

driveApp.delete('/shares/:id/members/:userId', async (c) => {
  const userId = c.req.param('userId');
  // The owner can remove anyone; a member may remove themselves (leave the share)
  // 所有者可移除任何人;成员可以移除自己(退出共享)
  if (userId === c.get('user').id) {
    await c.env.DB.prepare('DELETE FROM drive_share_members WHERE share_id=?1 AND user_id=?2')
      .bind(c.req.param('id'), userId).run();
    return c.json({ ok: true });
  }
  const s = await ownShare(c);
  await c.env.DB.prepare('DELETE FROM drive_share_members WHERE share_id=?1 AND user_id=?2')
    .bind(s.id, userId).run();
  return c.json({ ok: true });
});

// Opening a share link: same-domain users only; joining puts it under their "Shared with me"
// 打开共享链接:仅限同域用户;加入后出现在其「共享给我」列表
driveApp.post('/shares/join', async (c) => {
  const user = c.get('user');
  const token = String((await c.req.json<any>()).token || '');
  if (!token) throw new HttpError(400, 'e_bad_request');
  const s = await c.env.DB.prepare('SELECT * FROM drive_shares WHERE token=?1').bind(token).first<any>();
  if (!s) throw new HttpError(404, 'e_drive_share_not_found');
  const chain = await chainOf(c.env, s.node_id);
  if (!chain.length || chain.some((n) => n.trashed)) throw new HttpError(404, 'e_drive_share_not_found');
  if (s.owner_id !== user.id) {
    if (!(await sharesDomainWith(c.env, s.owner_id, user.id))) throw new HttpError(403, 'e_drive_share_domain');
    await c.env.DB.prepare('INSERT OR IGNORE INTO drive_share_members (share_id, user_id, joined_at) VALUES (?1,?2,?3)')
      .bind(s.id, user.id, now()).run();
  }
  return c.json({ node_id: s.node_id, name: chain[0].name, role: s.role });
});

driveApp.get('/shared', async (c) => {
  const rows = await c.env.DB.prepare(
    `SELECT s.id AS share_id, s.node_id, s.role, m.joined_at, u.name AS owner_name, u.email AS owner_email
     FROM drive_share_members m JOIN drive_shares s ON s.id=m.share_id JOIN users u ON u.id=s.owner_id
     WHERE m.user_id=?1 ORDER BY m.joined_at DESC LIMIT 200`
  ).bind(c.get('user').id).all();
  const out: any[] = [];
  for (const r of (rows.results || []) as any[]) {
    // Folders sitting in the owner's trash (or already purged) stay out of the list
    // 已进所有者回收站(或已删)的文件夹不出现在列表里
    const chain = await chainOf(c.env, r.node_id);
    if (!chain.length || chain.some((n) => n.trashed)) continue;
    out.push({ ...r, name: chain[0].name });
  }
  return c.json({ shares: out });
});

// ---------- Admin API (/api/admin/drive) ----------
// ---------- 管理端 API(/api/admin/drive) ----------

export const driveAdminApp = new Hono<Ctx>();

driveAdminApp.get('/domains', async (c) => {
  const scope = await adminScope(c);
  const rows = await c.env.DB.prepare('SELECT id, name, drive_enabled, drive_quota_mb FROM domains ORDER BY name').all();
  let list = (rows.results || []) as any[];
  if (scope) list = list.filter((d) => scope.has(d.id));
  return c.json({ domains: list, hard_cap_mb: DRIVE_HARD_CAP_MB });
});

driveAdminApp.post('/domains/:id', async (c) => {
  const id = c.req.param('id');
  await checkDomainScope(c, id);
  const body = await c.req.json<any>();
  const sets: string[] = [];
  const vals: any[] = [];
  if (body.enabled !== undefined) {
    sets.push(`drive_enabled=?${vals.length + 1}`);
    vals.push(body.enabled ? 1 : 0);
  }
  if (body.quota_mb !== undefined) {
    const q = Math.floor(Number(body.quota_mb));
    if (!Number.isFinite(q) || q < 1 || q > DRIVE_HARD_CAP_MB) throw new HttpError(400, 'e_drive_bad_quota');
    sets.push(`drive_quota_mb=?${vals.length + 1}`);
    vals.push(q);
  }
  if (sets.length) {
    vals.push(id);
    await c.env.DB.prepare(`UPDATE domains SET ${sets.join(',')} WHERE id=?${vals.length}`).bind(...vals).run();
    await audit(c.env, c.get('user'), 'drive.settings', undefined,
      { enabled: body.enabled, quota_mb: body.quota_mb }, id);
  }
  return c.json({ ok: true });
});

driveAdminApp.get('/users', async (c) => {
  const scope = await adminScope(c);
  const q = String(c.req.query('q') || '').trim().slice(0, 100);
  const binds: any[] = [];
  const where: string[] = [];
  if (scope) {
    const ids = [...scope];
    where.push(`EXISTS (SELECT 1 FROM grants g JOIN mailboxes mb ON mb.id=g.mailbox_id
      WHERE g.user_id=u.id AND mb.domain_id IN (${ids.map((_, i) => '?' + (binds.length + i + 1)).join(',')}))`);
    binds.push(...ids);
  }
  if (q) {
    const like = '%' + q.replace(/[\\%_]/g, (ch) => '\\' + ch) + '%';
    where.push(`(u.email LIKE ?${binds.length + 1} ESCAPE '\\' OR u.name LIKE ?${binds.length + 1} ESCAPE '\\')`);
    binds.push(like);
  }
  const rows = await c.env.DB.prepare(
    `SELECT u.id, u.email, u.name, u.drive_quota_mb AS user_mb, u.drive_bytes AS used,
       (SELECT COUNT(*) FROM drive_nodes n WHERE n.owner_id=u.id AND n.kind='file') AS files,
       (SELECT MAX(d.drive_quota_mb) FROM domains d WHERE d.drive_enabled=1 AND d.id IN
         (SELECT mb2.domain_id FROM grants g2 JOIN mailboxes mb2 ON mb2.id=g2.mailbox_id WHERE g2.user_id=u.id)) AS dom_mb
     FROM users u ${where.length ? 'WHERE ' + where.join(' AND ') : ''}
     ORDER BY used DESC, u.email LIMIT 200`
  ).bind(...binds).all();
  const users = ((rows.results || []) as any[]).map((r) => ({
    id: r.id, email: r.email, name: r.name,
    used: r.used || 0, files: r.files || 0,
    quota_mb: r.user_mb, default_mb: r.dom_mb,
    effective_mb: r.dom_mb == null ? 0 : Math.min(r.user_mb ?? r.dom_mb, DRIVE_HARD_CAP_MB),
    enabled: r.dom_mb != null,
  }));
  return c.json({ users, hard_cap_mb: DRIVE_HARD_CAP_MB });
});

driveAdminApp.post('/users/:id', async (c) => {
  const scope = await adminScope(c);
  const id = c.req.param('id');
  const target = await c.env.DB.prepare('SELECT id, email FROM users WHERE id=?1').bind(id).first<any>();
  if (!target) throw new HttpError(404, 'e_user_not_found');
  if (scope) {
    const ids = [...scope];
    const hit = await c.env.DB.prepare(
      `SELECT 1 AS ok FROM grants g JOIN mailboxes mb ON mb.id=g.mailbox_id
       WHERE g.user_id=?1 AND mb.domain_id IN (${ids.map((_, i) => '?' + (i + 2)).join(',')}) LIMIT 1`
    ).bind(id, ...ids).first();
    if (!hit) throw new HttpError(403, 'e_no_domain_perm');
  }
  const body = await c.req.json<any>();
  let quota: number | null = null;
  if (body.quota_mb !== null && body.quota_mb !== undefined && body.quota_mb !== '') {
    quota = Math.floor(Number(body.quota_mb));
    if (!Number.isFinite(quota) || quota < 1 || quota > DRIVE_HARD_CAP_MB) throw new HttpError(400, 'e_drive_bad_quota');
  }
  await c.env.DB.prepare('UPDATE users SET drive_quota_mb=?1 WHERE id=?2').bind(quota, id).run();
  await audit(c.env, c.get('user'), 'drive.quota', target.email, { quota_mb: quota });
  return c.json({ ok: true });
});

// ---------- Cron hooks ----------
// ---------- 定时任务 ----------

/** Hourly: abort multipart uploads that never completed
 *  每小时:中止一直没完成的分片上传 */
export async function driveCronHourly(env: Env): Promise<void> {
  const olds = await env.DB.prepare('SELECT * FROM drive_uploads WHERE created_at<?1 LIMIT 50')
    .bind(now() - UPLOAD_STALE_MS).all();
  for (const u of (olds.results || []) as any[]) {
    try {
      await env.RAW.resumeMultipartUpload(u.r2_key, u.upload_id).abort();
    } catch {}
    await env.DB.prepare('DELETE FROM drive_uploads WHERE id=?1').bind(u.id).run();
  }
}

/** Daily: purge trash older than 30 days, bounded per run (a huge subtree simply continues tomorrow)
 *  每天:清理回收站中超过 30 天的内容,每次运行有上限(特别大的子树明天接着删) */
export async function driveCronDaily(env: Env): Promise<void> {
  for (let i = 0; i < 3; i++) {
    const row = await env.DB.prepare('SELECT id FROM drive_nodes WHERE trashed=1 AND trashed_at<?1 LIMIT 1')
      .bind(now() - TRASH_KEEP_MS).first<any>();
    if (!row) break;
    await purgeSubtree(env, row.id, PURGE_BATCH);
  }
}
