// Generated by scripts/build-themes.mjs -- do not edit by hand
export const THEME_NAMES = ["tomato","red","ruby","crimson","pink","plum","purple","violet","iris","indigo","blue","sky","cyan","mint","teal","jade","green","grass","lime","yellow","amber","orange","brown","gold","bronze","mono-gray","mono-mauve","mono-slate","mono-sage","mono-sand"];
